import {V,M,uid,clamp} from '../core/math.js';
import {NurbsCurve,NurbsSurface,circleCurve,interpolateCurve,polyline,rectangle,loftSurface,revolveSurface,sweepSurface,transformGeometry,geometryMesh,offsetPlanarCurve,canopySurface} from '../core/geometry.js';
import {mesh,mergeMeshes,analyzeMesh,subdivideMesh,weldMesh,sectionMesh,recomputeNormals} from '../core/mesh.js';
import {booleanMesh} from '../core/csg.js';
import {download,exportOBJ,exportSTL,exportDXF,exportGLTF} from '../core/io.js';
import {formDialog,toast} from './ui.js';
const f=(key,label,value,min,max)=>({key,label,value,min,max});
export class Commands{
  constructor(app){this.app=app;this.items=new Map();this.install();}
  add(id,label,category,icon,run,shortcut=''){this.items.set(id,{id,label,category,icon,run,shortcut});}
  async execute(text){let tokens=text.trim().match(/"[^"]*"|[^\s]+/g)??[],name=tokens.shift()?.toLowerCase().replace(/^_/,'');if(!name)return;let aliases={selall:'selectall',selnone:'deselect',del:'delete',interpcurve:'interpcurve',booleanunion:'union',booleandifference:'difference',booleanintersection:'intersection',zoom:'zoomextents','4view':'fourview',pointson:'points',grasshopper:'weave'};name=aliases[name]??name;let c=this.items.get(name);if(!c)throw Error('Unknown command: '+name+'. Press / to search implemented commands.');this.app.lastCommand=name;let args=tokens.map(s=>s.replace(/^"|"$/g,''));this.app.log(c.label);return await c.run(args);}
  selected(kind,min=1){let s=this.app.doc.selected();if(s.length<min)throw Error(`Select ${min===1?'an object':`at least ${min} objects`} first`);if(kind&&s.some(o=>o.geometry.kind!==kind))throw Error('Select '+kind+' objects for this operation');return s;}
  addGeometry(g,name,options={}){let doc=this.app.doc;return doc.transaction(name,()=>{let o=doc.add(g,name,options);doc.select([o.id]);return o;});}
  async params(args,title,fields,description='',submit='Create'){if(args.length){let data={};for(let i=0;i<fields.length;i++){let field=fields[i];data[field.key]=args[i]!==undefined?Number(args[i]):field.value;if(!Number.isFinite(data[field.key])||(field.min!==undefined&&data[field.key]<field.min)||(field.max!==undefined&&data[field.key]>field.max))throw Error('Invalid '+field.label);}return data;}return formDialog(title,fields,{description,submit});}
  install(){let app=this.app,doc=app.doc,add=(...a)=>this.add(...a);
    add('new','New document','File','new',()=>app.newDocument(),'Ctrl+N');add('open','Open / import file','File','open',()=>app.openFile(),'Ctrl+O');add('import','Import geometry','File','import',()=>app.openFile());add('save','Save Veldra document','File','save',()=>app.save(),'Ctrl+S');add('saveas','Save document as…','File','save',async()=>{let v=await formDialog('Save document',[{key:'name',label:'Document name',value:doc.name,type:'text'}],{submit:'Save'});if(v){doc.name=v.name;app.save();doc.notify('name');}});
    for(let [id,label,fn,ext] of [['exportobj','Export Wavefront OBJ',exportOBJ,'obj'],['exportstl','Export binary STL',o=>exportSTL(o.map(e=>e.mesh).filter(Boolean)),'stl'],['exportdxf','Export DXF entities',exportDXF,'dxf'],['exportgltf','Export glTF 2.0',exportGLTF,'gltf']])add(id,label,'File','export',()=>{let entries=app.exportEntries();if(!entries.length)throw Error('No geometry to export');download(fn(entries),doc.name+'.'+ext);app.log('Exported '+entries.length+' objects to '+ext.toUpperCase());});
    add('saveweave','Save Weave definition','Weave','save',()=>download(JSON.stringify(app.graph.serialize(),null,2),doc.name+'.weave','application/json'));
    add('undo','Undo','Edit','undo',()=>{let label=app.graphView.selected?app.graphView.undo():doc.undo();if(!label)toast('Nothing to undo');},'Ctrl+Z');add('redo','Redo','Edit','redo',()=>{let label=app.graphView.selected?app.graphView.redo():doc.redo();if(!label)toast('Nothing to redo');},'Ctrl+Y');
    add('delete','Delete selected','Edit','delete',()=>{this.selected();doc.transaction('Delete',()=>doc.removeSelected());},'Delete');
    add('copy','Copy','Edit','copy',()=>{app.clipboard=structuredClone(this.selected());toast('Copied '+app.clipboard.length+' objects');},'Ctrl+C');
    add('paste','Paste','Edit','copy',()=>{if(!app.clipboard?.length)throw Error('Copy document objects first');doc.transaction('Paste',()=>{let created=app.clipboard.map(o=>{let copy=structuredClone(o);copy.id=uid();copy.name+=' copy';copy.matrix=M.mul(M.translation([2,2,0]),copy.matrix);doc.objects.push(copy);return copy;});doc.select(created.map(o=>o.id));});},'Ctrl+V');
    add('duplicate','Duplicate','Edit','copy',()=>{let objects=this.selected();doc.transaction('Duplicate',()=>{let created=objects.map(o=>{let copy=structuredClone(o);copy.id=uid();copy.name+=' copy';copy.matrix=M.mul(M.translation([2,2,0]),copy.matrix);doc.objects.push(copy);return copy;});doc.select(created.map(o=>o.id));});},'Ctrl+D');
    add('selectall','Select all','Edit','select',()=>{app.graphView.select(null);doc.select(doc.visibleObjects().map(o=>o.id));},'Ctrl+A');add('deselect','Deselect all','Edit','select',()=>{doc.select([]);app.graphView.select(null);},'Esc');add('select','Select objects','Edit','select',()=>app.cancelTool());
    add('hide','Hide selected','Edit','eye',()=>{let s=this.selected();doc.transaction('Hide',()=>{s.forEach(o=>o.visible=false);doc.selection.clear();});});add('show','Show all objects','Edit','eye',()=>doc.transaction('Show all',()=>doc.objects.forEach(o=>o.visible=true)));add('lock','Lock selected','Edit','lock',()=>{let s=this.selected();doc.transaction('Lock',()=>{s.forEach(o=>o.locked=true);doc.selection.clear();});});add('unlock','Unlock all objects','Edit','lock',()=>doc.transaction('Unlock',()=>doc.objects.forEach(o=>o.locked=false)));
    add('move','Move by vector','Transform','move',async args=>{let s=this.selected(),p=await this.params(args,'Move objects',[f('x','X translation',0),f('y','Y translation',0),f('z','Z translation',5)],'Translations are in document units.','Move');if(p)doc.transaction('Move',()=>s.forEach(o=>{o.matrix=M.mul(M.translation([p.x,p.y,p.z]),o.matrix);doc.touch(o);}));},'M');
    add('rotate','Rotate around world Z','Transform','rotate',async args=>{let s=this.selected(),p=await this.params(args,'Rotate objects',[f('angle','Angle in degrees',45),f('x','Pivot X',0),f('y','Pivot Y',0),f('z','Pivot Z',0)],'Positive angles rotate counterclockwise around the world Z axis.','Rotate');if(p){let center=[p.x,p.y,p.z],mat=M.mul(M.translation(center),M.mul(M.rotation([0,0,1],p.angle*Math.PI/180),M.translation(V.mul(center,-1))));doc.transaction('Rotate',()=>s.forEach(o=>{o.matrix=M.mul(mat,o.matrix);doc.touch(o);}));}});
    add('scale','Scale objects','Transform','scale',async args=>{let s=this.selected(),p=await this.params(args,'Scale objects',[f('factor','Uniform scale factor',1.5,.0001,1e6)],'Scales about the selection bounding-box center.','Scale');if(p){let c=doc.bounds(true).center,mat=M.mul(M.translation(c),M.mul(M.scaling(p.factor),M.translation(V.mul(c,-1))));doc.transaction('Scale',()=>s.forEach(o=>{o.matrix=M.mul(mat,o.matrix);doc.touch(o);}));}});
    add('mirror','Mirror across YZ plane','Transform','mirror',()=>{let s=this.selected();doc.transaction('Mirror',()=>s.forEach(o=>{let copy=structuredClone(o);copy.id=uid();copy.name+=' mirrored';copy.matrix=M.mul(M.scaling([-1,1,1]),copy.matrix);doc.objects.push(copy);}));});
    add('array','Linear array','Transform','array',async args=>{let s=this.selected(),p=await this.params(args,'Linear array',[f('count','Total copies (including source)',5,2,200),f('x','Step X',8),f('y','Step Y',0),f('z','Step Z',0)],'Each instance retains its editable source geometry.','Array');if(p)doc.transaction('Linear array',()=>{let ids=[];for(let i=1;i<Math.floor(p.count);i++)for(let o of s){let copy=structuredClone(o);copy.id=uid();copy.name+=` / ${i+1}`;copy.matrix=M.mul(M.translation([p.x*i,p.y*i,p.z*i]),copy.matrix);doc.objects.push(copy);ids.push(copy.id);}doc.select(ids);});});
    add('polararray','Polar array','Transform','array',async args=>{let s=this.selected(),p=await this.params(args,'Polar array',[f('count','Total copies',8,2,200),f('angle','Sweep angle in degrees',360,-360,360)],'Rotates copies around the world Z axis.','Array');if(p)doc.transaction('Polar array',()=>{for(let i=1;i<Math.floor(p.count);i++)for(let o of s){let copy=structuredClone(o);copy.id=uid();copy.name+=` / ${i+1}`;copy.matrix=M.mul(M.rotation([0,0,1],p.angle*Math.PI/180*i/p.count),copy.matrix);doc.objects.push(copy);}});});
    for(let [id,label,ico] of [['point','Point','point'],['line','Line','line'],['polyline','Polyline','polyline'],['curve','Control-point curve','curve'],['interpcurve','Interpolated curve','curve'],['circle','Circle','circle'],['rectangle','Rectangle','rectangle'],['distance','Measure distance','measure']])add(id,label,id==='distance'?'Analysis':'Curve',ico,()=>app.beginTool(id));
    add('arc','Circular arc','Curve','arc',async args=>{let p=await this.params(args,'Arc',[f('radius','Radius',5,.001),f('start','Start angle in degrees',0),f('sweep','Sweep angle in degrees',120,-360,360)]);if(p)this.addGeometry(circleCurve([0,0,0],p.radius,p.start*Math.PI/180,p.sweep*Math.PI/180).toJSON(),'Arc');});
    add('ellipse','Ellipse','Curve','ellipse',async args=>{let p=await this.params(args,'Ellipse',[f('rx','X radius',8,.001),f('ry','Y radius',4,.001)]);if(p)this.addGeometry(transformGeometry(circleCurve([0,0,0],1).toJSON(),M.scaling([p.rx,p.ry,1])),'Ellipse');});
    add('polygon','Regular polygon','Curve','polygon',async args=>{let p=await this.params(args,'Regular polygon',[f('radius','Circumradius',5,.001),f('sides','Sides',6,3,100)]);if(p)this.addGeometry(polyline(Array.from({length:Math.floor(p.sides)},(_,i)=>[p.radius*Math.cos(i*2*Math.PI/Math.floor(p.sides)),p.radius*Math.sin(i*2*Math.PI/Math.floor(p.sides)),0]),true),'Polygon');});
    add('helix','Helix','Curve','helix',async args=>{let p=await this.params(args,'Helix',[f('radius','Radius',4,.001),f('height','Height',15),f('turns','Turns',3,.1,30)]);if(p){let n=Math.ceil(p.turns*24),points=Array.from({length:n+1},(_,i)=>[p.radius*Math.cos(i/n*p.turns*Math.PI*2),p.radius*Math.sin(i/n*p.turns*Math.PI*2),i/n*p.height]);this.addGeometry(interpolateCurve(points,3).toJSON(),'Helix (interpolated)');}});
    const primitives=[['box','Box','box',[f('width','Width X',8,.001),f('depth','Depth Y',6,.001),f('height','Height Z',5,.001)]],['sphere','Sphere','sphere',[f('radius','Radius',4,.001)]],['cylinder','Cylinder','cylinder',[f('radius','Radius',3,.001),f('height','Height',8,.001)]],['cone','Cone','cone',[f('radius','Base radius',4,.001),f('height','Height',9,.001)]],['torus','Torus','torus',[f('major','Major radius',6,.001),f('minor','Minor radius',1.5,.001)]]];
    for(let [id,label,ico,fields] of primitives)add(id,label,'Solid',ico,async args=>{let p=await this.params(args,label,fields);if(!p)return;if(id==='torus'&&p.minor>=p.major)throw Error('Major radius must exceed minor radius');let kind=id==='cone'?'cylinder':id,g={kind,...p,...(id==='cone'?{topRadius:0}:{})};this.addGeometry(g,label,{matrix:M.translation(id==='sphere'?[0,0,p.radius]:id==='torus'?[0,0,p.minor]:[0,0,0])});});
    add('plane','Planar NURBS surface','Surface','plane',async args=>{let p=await this.params(args,'Plane',[f('width','Width',10,.001),f('depth','Depth',10,.001)]);if(p)this.addGeometry(new NurbsSurface([[[-p.width/2,-p.depth/2,0],[p.width/2,-p.depth/2,0]],[[-p.width/2,p.depth/2,0],[p.width/2,p.depth/2,0]]],1,1).toJSON(),'Plane');});
    add('surface','Freeform NURBS surface','Surface','surface',async args=>{let p=await this.params(args,'Freeform surface',[f('span','Span',18,.1),f('rise','Rise',7,.1),f('twist','Twist',5),f('depth','Depth',10,.1)],'Creates a tensor-product NURBS patch. Use Points to edit the control net.');if(p)this.addGeometry(canopySurface(p.span,p.rise,p.twist,p.depth),'NURBS surface');});
    add('loft','Loft through curves','Surface','loft',()=>{let s=this.selected('curve',2),curves=s.map(o=>transformGeometry(o.geometry,o.matrix));this.addGeometry(loftSurface(curves).toJSON(),'Loft');});
    add('extrude','Extrude curve','Surface','extrude',async args=>{let s=this.selected('curve'),p=await this.params(args,'Extrude curves',[f('height','Extrusion along world Z',10)],'Closed planar profiles are capped. Open profiles produce open surfaces.');if(p)doc.transaction('Extrude',()=>{let ids=[];for(let o of s){let n=doc.add({kind:'extrusion',profile:transformGeometry(o.geometry,o.matrix),vector:[0,0,p.height],cap:true},'Extrusion');geometryMesh(n.geometry);ids.push(n.id);}doc.select(ids);});});
    add('revolve','Revolve profile','Surface','revolve',async args=>{let s=this.selected('curve'),p=await this.params(args,'Revolve curves',[f('angle','Angle in degrees',360,-360,360)],'Draw the profile in the Front viewport. The rotation axis is world Z.');if(p)doc.transaction('Revolve',()=>{let ids=s.map(o=>doc.add(revolveSurface(transformGeometry(o.geometry,o.matrix),p.angle*Math.PI/180).toJSON(),'Revolved surface').id);doc.select(ids);});});
    add('sweep','Sweep profile along rail','Surface','sweep',()=>{let s=this.selected('curve',2);if(s.length!==2)throw Error('Select exactly two curves: profile first in document order, then rail');let [p,r]=s.map(o=>transformGeometry(o.geometry,o.matrix));this.addGeometry(sweepSurface(p,r).toJSON(),'Sweep');});
    add('pipe','Pipe along curve','Surface','pipe',async args=>{let s=this.selected('curve'),p=await this.params(args,'Pipe',[f('radius','Pipe radius',.35,.001)],'Uses parallel-transport frames along the rail.');if(p)doc.transaction('Pipe',()=>{let ids=s.map(o=>doc.add({kind:'pipe',rail:transformGeometry(o.geometry,o.matrix),radius:p.radius},'Pipe').id);doc.select(ids);});});
    add('offset','Offset XY-planar curve','Curve','offset',async args=>{let s=this.selected('curve'),p=await this.params(args,'Offset curve',[f('distance','Offset distance',1)],'Produces a sampled miter-joined polyline. Positive distance offsets left relative to curve direction.');if(p)doc.transaction('Offset',()=>{let ids=s.map(o=>doc.add(offsetPlanarCurve(transformGeometry(o.geometry,o.matrix),p.distance),'Offset polyline').id);doc.select(ids);});});
    add('reverse','Reverse curve direction','Curve','rotate',()=>{let s=this.selected('curve');doc.transaction('Reverse curve',()=>s.forEach(o=>{o.geometry=NurbsCurve.from(o.geometry).reverse().toJSON();doc.touch(o);}));});
    add('insertknot','Insert curve knot','Curve','points',async args=>{let s=this.selected('curve'),p=await this.params(args,'Insert knot',[f('parameter','Normalized parameter',.5,.00001,.99999)],'Adds a control point without changing the curve shape.','Insert');if(p)doc.transaction('Insert knot',()=>s.forEach(o=>{o.geometry=NurbsCurve.from(o.geometry).insertKnot(p.parameter).toJSON();doc.touch(o);}));});
    add('splitcurve','Split curve at parameter','Curve','split',async args=>{let s=this.selected('curve'),p=await this.params(args,'Split curve',[f('parameter','Normalized split parameter',.5,.00001,.99999)],'Produces two exact rational B-spline curves.','Split');if(p)doc.transaction('Split curve',()=>{let ids=[];for(let o of s){let pieces=NurbsCurve.from(o.geometry).split(p.parameter);for(let c of pieces)ids.push(doc.add(c.toJSON(),o.name+' split',{matrix:[...o.matrix],color:o.color}).id);doc.objects=doc.objects.filter(q=>q.id!==o.id);}doc.select(ids);});});
    add('rebuild','Rebuild curve by interpolation','Curve','curve',async args=>{let s=this.selected('curve'),p=await this.params(args,'Rebuild curve',[f('samples','Sample count',16,4,100),f('degree','Degree',3,1,7)],'This is an approximation through uniformly parameterized samples, not shape-preserving degree elevation.','Rebuild');if(p)doc.transaction('Rebuild',()=>s.forEach(o=>{o.geometry=interpolateCurve(NurbsCurve.from(o.geometry).sample(Math.floor(p.samples)-1),Math.floor(p.degree)).toJSON();doc.touch(o);}));});
    add('join','Join sampled curves','Curve','join',()=>{let s=this.selected('curve',2),remaining=s.map(o=>NurbsCurve.from(transformGeometry(o.geometry,o.matrix)).tessellate(.01)),points=remaining.shift();while(remaining.length){let best=Infinity,index=-1,reverse=false;for(let i=0;i<remaining.length;i++)for(let r=0;r<2;r++){let distance=V.distance(points.at(-1),r?remaining[i].at(-1):remaining[i][0]);if(distance<best){best=distance;index=i;reverse=!!r;}}if(best>doc.tolerance*10)throw Error('Curve endpoints do not meet within 10 × document tolerance');let next=remaining.splice(index,1)[0];if(reverse)next.reverse();points.push(...next.slice(1));}this.addGeometry(polyline(points),'Joined polyline');});
    add('mesh','Convert to mesh','Mesh','mesh',()=>{let s=this.selected();doc.transaction('Mesh',()=>{let ids=s.map(o=>{let m=doc.display(o).mesh;if(!m)throw Error('Select surface or solid geometry');return doc.add(structuredClone(m),o.name+' mesh',{color:o.color}).id;});doc.select(ids);});});
    add('subdivide','Loop subdivision','Mesh','subdivide',async args=>{let s=this.selected(),p=await this.params(args,'Loop subdivision',[f('iterations','Iterations',1,1,3)],'Smooths a welded triangle mesh using interior and boundary Loop rules.','Subdivide');if(p)doc.transaction('Subdivision',()=>{let ids=s.map(o=>{let m=doc.display(o).mesh;if(!m)throw Error('Select surface or mesh geometry');return doc.add(subdivideMesh(m,Math.floor(p.iterations)),o.name+' subdivided',{color:o.color}).id;});doc.select(ids);});});
    add('weld','Weld mesh vertices','Mesh','join',()=>{let s=this.selected('mesh');doc.transaction('Weld',()=>s.forEach(o=>{o.geometry=weldMesh(o.geometry,doc.tolerance);doc.touch(o);}));});
    add('flip','Flip mesh normals','Mesh','rotate',()=>{let s=this.selected('mesh');doc.transaction('Flip normals',()=>s.forEach(o=>{for(let i=0;i<o.geometry.indices.length;i+=3)[o.geometry.indices[i+1],o.geometry.indices[i+2]]=[o.geometry.indices[i+2],o.geometry.indices[i+1]];recomputeNormals(o.geometry);doc.touch(o);}));});
    for(let [id,label] of [['union','Mesh Boolean union'],['difference','Mesh Boolean difference'],['intersection','Mesh Boolean intersection']])add(id,label,'Solid',id,()=>{let s=this.selected(null,2);if(s.length!==2)throw Error('Select exactly two closed solids');let a=doc.display(s[0],.5).mesh,b=doc.display(s[1],.5).mesh;if(!a||!b)throw Error('Select two meshable closed solids');let result=booleanMesh(a,b,id,Math.max(doc.tolerance*.01,1e-7));doc.transaction(label,()=>{s.forEach(o=>o.visible=false);let o=doc.add(result,label,{color:s[0].color});doc.select([o.id]);});toast('Boolean result is a polygon mesh; sources are hidden, not deleted.');});
    add('section','Section at world Z','Analysis','section',async args=>{let s=this.selected(),p=await this.params(args,'Create section',[f('height','Section Z',5)],'Intersects display triangles with a horizontal plane. Output consists of line segments.');if(p)doc.transaction('Section',()=>{let ids=s.map(o=>{let m=doc.display(o).mesh;if(!m)throw Error('Select a surface or solid');return doc.add({kind:'lines',segments:sectionMesh(m,[0,0,p.height])},'Section @ '+p.height,{color:'#c27842'}).id;});doc.select(ids);});});
    add('analyze','Analyze selection','Analysis','analyze',()=>app.showAnalysis(this.selected()));
    add('length','Curve length','Analysis','measure',()=>{let s=this.selected('curve'),length=s.reduce((sum,o)=>sum+NurbsCurve.from(transformGeometry(o.geometry,o.matrix)).length(doc.tolerance*.1),0);app.log(`Curve length: ${length.toFixed(6)} ${doc.units}`);toast(`Length: ${length.toFixed(4)} ${doc.units}`);});
    add('clip','Clipping plane','View','section',async args=>{let p=await this.params(args,'Clipping plane',[f('height','Keep geometry above world Z',3)],'Visual clipping only; no topology is changed. Run ClipOff to remove.','Apply');if(p){app.renderer.clip=[0,0,1,-p.height];app.renderer.clipOn=true;app.invalidate();}});add('clipoff','Disable clipping','View','section',()=>{app.renderer.clipOn=false;app.invalidate();});
    add('zoomextents','Zoom extents','View','fit',()=>app.fit(false),'Home');add('zoomselected','Zoom selected','View','fit',()=>app.fit(true),'F');add('fourview','Four viewports / maximize','View','fourview',()=>app.toggleFour(),'F4');
    for(let view of ['Perspective','Top','Front','Right'])add(view.toLowerCase(),view+' view','View',view==='Perspective'?'box':'plane',()=>app.setView(view));
    for(let [id,label] of [['grid','Construction grid'],['snap','Grid snapping'],['ortho','Ortho mode'],['osnap','Object snapping'],['gumball','Transform gumball'],['points','Control points']])add(id,label,'View',id==='gumball'?'move':id==='points'?'points':'grid',()=>app.toggle(id));
    for(let [id,label,mode] of [['wireframe','Wireframe',1],['shaded','Shaded',0],['rendered','Rendered',2],['zebra','Zebra analysis',3],['normals','Normal analysis',4]])add(id,label,'View',id==='zebra'?'analyze':'render',()=>app.setDisplay(mode));
    add('edges','Toggle surface isocurves / edges','View','curve',()=>{app.renderer.showEdges=!app.renderer.showEdges;app.invalidate();});
    add('weave','Show / hide Weave','Weave','weave',()=>app.toggleWeave(),'W');add('bake','Bake preview geometry','Weave','extrude',()=>app.bake());add('component','Add a component','Weave','weave',()=>app.graphView.library(),'Space');add('solver','Pause / resume solver','Weave','play',()=>{app.graph.enabled=!app.graph.enabled;app.graph.changed('solver');});add('modelworkspace','Model workspace','View','box',()=>app.setWorkspace(false));add('paramworkspace','Parametric workspace','View','weave',()=>app.setWorkspace(true));
    add('units','Document units and tolerance','File','gear',async()=>{let p=await formDialog('Document settings',[{key:'units',label:'Units (labels only; does not rescale geometry)',type:'select',options:['mm','cm','m','in','ft'],value:doc.units},f('tolerance','Absolute modeling tolerance',doc.tolerance,.0000001,100)],{submit:'Apply'});if(p)doc.transaction('Document settings',()=>{doc.units=p.units;doc.tolerance=p.tolerance;});});
    add('layer','Add layer','Edit','new',async()=>{let p=await formDialog('New layer',[{key:'name',label:'Name',value:'Layer '+(doc.layers.length+1),type:'text'},{key:'color',label:'Color',value:'#749ba3',type:'color'}],{submit:'Add layer'});if(p)doc.transaction('Add layer',()=>{let l={id:uid('l'),name:p.name,color:p.color,visible:true,locked:false};doc.layers.push(l);doc.currentLayer=l.id;});});
    add('reference','Reference selection in Weave','Weave','weave',()=>{let s=this.selected();app.graphView.edit(()=>{for(let i=0;i<s.length;i++)app.graph.add('reference',60+i*210,420,{objectId:s[i].id});});app.graphView.fit();});
    add('screenshot','Save viewport PNG','File','render',()=>app.capture());
    add('demo','Open canopy example','File','surface',()=>app.loadDemo());add('about','About Veldra','Help','info',()=>app.showAbout());add('help','Commands and navigation','Help','info',()=>app.showHelp(),'?');add('gpuevaluate','Evaluate selected surface on GPU','Analysis','analyze',async()=>{let s=this.selected('surface'),start=performance.now(),p=await app.renderer.computeSurface(s[0].geometry,96,64);toast(`GPU evaluated ${p.length/4} surface points in ${(performance.now()-start).toFixed(1)} ms including readback.`);});
  }
}
export const MENUS={File:['new','open','demo',null,'save','saveas','saveweave',null,'exportobj','exportstl','exportdxf','exportgltf','screenshot',null,'units'],Edit:['undo','redo',null,'copy','paste','duplicate','delete',null,'selectall','deselect','hide','show','lock','unlock','layer'],View:['perspective','top','front','right','fourview',null,'zoomextents','zoomselected',null,'wireframe','shaded','rendered','zebra','normals','edges',null,'grid','points','gumball','clip','clipoff'],Curve:['point','line','polyline','curve','interpcurve','circle','arc','ellipse','rectangle','polygon','helix',null,'offset','join','reverse','insertknot','splitcurve','rebuild'],Surface:['plane','surface','loft','extrude','revolve','sweep','pipe'],Solid:['box','sphere','cylinder','cone','torus',null,'union','difference','intersection'],Mesh:['mesh','subdivide','weld','flip'],Transform:['move','rotate','scale','mirror','array','polararray'],Analyze:['distance','length','analyze','section','zebra','normals','gpuevaluate'],Weave:['weave','component','solver','bake','reference','saveweave'],Help:['help','about']};
export const TOOLBARS={Standard:['new','open','save',null,'undo','redo',null,'select','move','rotate','scale',null,'curve','circle',null,'box','loft','extrude',null,'zoomextents','fourview'],Curves:['point','line','polyline','curve','interpcurve','circle','arc','ellipse','rectangle','polygon','helix',null,'offset','splitcurve','insertknot'],Surfaces:['plane','surface','loft','extrude','revolve','sweep','pipe',null,'points','mesh','analyze'],Solids:['box','sphere','cylinder','cone','torus',null,'union','difference','intersection',null,'section'],Mesh:['mesh','subdivide','weld','flip',null,'union','difference','intersection','analyze'],Transform:['move','rotate','scale','mirror','array','polararray',null,'copy','duplicate','delete'],Analysis:['distance','length','analyze','section','zebra','normals','gpuevaluate',null,'clip','clipoff'],Weave:['weave','component','solver','bake','reference','saveweave']};
