import {$,$$,escape,icon,menu,searchPopup,toast} from './ui.js';
import {clamp} from '../core/math.js';
export class GraphView{
  constructor(graph,{onSelect=()=>{},onChange=()=>{}}={}){this.graph=graph;this.onSelect=onSelect;this.onChange=onChange;this.canvas=$('#graph-canvas');this.world=$('#graph-world');this.nodes=$('#graph-nodes');this.svg=$('#graph-wires');this.scale=.7;this.offset=[30,0];this.selected=null;this.wireSelected=null;this.undoStack=[];this.redoStack=[];this.drag=null;this.install();this.render();}
  snapshot(){this.undoStack.push(this.graph.serialize());if(this.undoStack.length>80)this.undoStack.shift();this.redoStack=[];}
  edit(fn){this.snapshot();try{fn();}catch(e){this.undoStack.pop();toast(e.message,true);}}
  undo(){let d=this.undoStack.pop();if(!d)return false;this.redoStack.push(this.graph.serialize());this.graph.restore(d);return true;}
  redo(){let d=this.redoStack.pop();if(!d)return false;this.undoStack.push(this.graph.serialize());this.graph.restore(d);return true;}
  nodeHeight(n){let d=this.graph.registry[n.type];return n.type==='number'?70:28+17+Math.max(d.inputs.length,d.outputs.length)*20+(n.type==='panel'?57:0);}
  portPosition(id,index,output){let n=this.graph.nodes.find(n=>n.id===id);return [n.x+(output?181:0),n.y+(n.type==='number'?49:47+index*20)];}
  nodeDOM(n){let d=this.graph.registry[n.type],rows=Math.max(d.inputs.length,d.outputs.length),status=this.graph.cache.get(n.id);let body=n.type==='number'?`<div class="node-slider"><input type="range" min="${n.params.min}" max="${n.params.max}" step="${n.params.step}" value="${n.params.value}" aria-label="${escape(n.label)}"><input type="number" value="${n.params.value}" step="${n.params.step}" aria-label="${escape(n.label)} value"></div><span class="port out" data-port="0" title="Value (number)"></span>`:`<div class="node-content">${Array.from({length:rows},(_,i)=>`<div class="node-port-row">${d.inputs[i]?`<span class="port in ${this.graph.wires.some(w=>w.to===n.id&&w.input===i)?'connected':''}" data-port="${i}" title="${escape(d.inputs[i].name)} (${d.inputs[i].type})"></span><span>${escape(d.inputs[i].name)}</span>`:''}${d.outputs[i]?`<span class="out-label">${escape(d.outputs[i].name)}</span><span class="port out" data-port="${i}" title="${escape(d.outputs[i].name)} (${d.outputs[i].type})"></span>`:''}</div>`).join('')}</div>${n.type==='panel'?'<div class="node-result"></div>':''}`;
    return `<article class="graph-node ${n.type==='number'?'node-number':''} ${this.selected===n.id?'selected':''} ${status?.error?'error':''}" data-id="${n.id}" style="left:${n.x}px;top:${n.y}px"><header class="node-header"><span class="node-category">${escape(d.category[0])}</span><span class="node-title">${escape(n.label??d.name)}</span>${d.outputs.some(o=>['geometry','curve','surface','mesh'].includes(o.type))?`<span class="node-preview ${n.preview?'active':''}" title="Toggle output preview"></span>`:''}</header>${body}<div class="node-error"></div></article>`;
  }
  render(){this.nodes.innerHTML=this.graph.nodes.map(n=>this.nodeDOM(n)).join('');this.refresh();this.transform();}
  refresh(){for(let n of this.graph.nodes){let el=$(`[data-id="${n.id}"]`,this.nodes);if(!el)continue;let c=this.graph.cache.get(n.id);el.classList.toggle('error',!!c?.error);el.classList.toggle('selected',this.selected===n.id);$('.node-error',el).textContent=c?.error??'';if(n.type==='panel')$('.node-result',el).textContent=c?.error?'':format(c?.values[0]);if(n.type==='number')for(let input of $$('input',el))if(document.activeElement!==input)input.value=n.params.value;$('.node-preview',el)?.classList.toggle('active',n.preview);}
    this.drawWires();$('#graph-status').textContent=`${this.graph.nodes.length} components · ${this.graph.wires.length} connections · ${this.graph.solveTime.toFixed(1)} ms${this.graph.errorCount?' · '+this.graph.errorCount+' errors':''}`;$('#graph-play').innerHTML=icon(this.graph.enabled?'pause':'play');$('#graph-play').title=this.graph.enabled?'Pause solver':'Resume solver';$('.live-badge').innerHTML=`<i></i> ${this.graph.enabled?'LIVE':'PAUSED'}`;
  }
  drawWires(){let paths=this.graph.wires.map(w=>{let a=this.portPosition(w.from,w.output,true),b=this.portPosition(w.to,w.input,false),dx=Math.max(35,Math.abs(b[0]-a[0])*.5);return `<path data-wire="${w.id}" class="${this.wireSelected===w.id?'selected':''}" d="M${a} C${a[0]+dx},${a[1]} ${b[0]-dx},${b[1]} ${b}"/>`;});if(this.drag?.kind==='wire'){let a=this.drag.start,b=this.drag.end,dx=Math.max(35,Math.abs(b[0]-a[0])*.5);paths.push(`<path class="drag-wire" d="M${a} C${a[0]+dx},${a[1]} ${b[0]-dx},${b[1]} ${b}"/>`);}this.svg.innerHTML=paths.join('');}
  transform(){this.world.style.transform=`translate(${this.offset[0]}px,${this.offset[1]}px) scale(${this.scale})`;$('#graph-zoom').textContent=Math.round(this.scale*100)+'%';this.canvas.style.backgroundSize=`${20*this.scale}px ${20*this.scale}px`;this.canvas.style.backgroundPosition=`${this.offset[0]}px ${this.offset[1]}px`;}
  fit(){if(!this.graph.nodes.length)return;let xs=this.graph.nodes.map(n=>n.x),ys=this.graph.nodes.map(n=>n.y),minX=Math.min(...xs),minY=Math.min(...ys),maxX=Math.max(...xs)+195,maxY=Math.max(...this.graph.nodes.map(n=>n.y+this.nodeHeight(n)));this.scale=clamp(Math.min((this.canvas.clientWidth-70)/(maxX-minX),(this.canvas.clientHeight-30)/(maxY-minY)),.25,1.1);this.offset=[(this.canvas.clientWidth-(maxX-minX)*this.scale)/2-minX*this.scale,(this.canvas.clientHeight-(maxY-minY)*this.scale)/2-minY*this.scale];this.transform();}
  toWorld(x,y){let r=this.canvas.getBoundingClientRect();return [(x-r.left-this.offset[0])/this.scale,(y-r.top-this.offset[1])/this.scale];}
  select(id){this.selected=id;this.wireSelected=null;for(let el of $$('.graph-node',this.nodes))el.classList.toggle('selected',el.dataset.id===id);this.onSelect(id);}
  library(x,y,category){let rect=this.canvas.getBoundingClientRect(),at=this.toWorld(x??rect.left+this.canvas.clientWidth*.45,y??rect.top+this.canvas.clientHeight*.4);searchPopup({title:'Search 57 components…',items:Object.entries(this.graph.registry).filter(([_,d])=>!category||d.category===category).map(([id,d])=>({id,label:d.name,category:d.category,icon:({Params:'weave',Math:'analyze',Vector:'move',Curve:'curve',Surface:'surface',Solid:'box',Transform:'move',Mesh:'mesh',Analysis:'analyze',Sets:'array'})[d.category]})),onChoose:item=>this.edit(()=>{let n=this.graph.add(item.id,...at);this.select(n.id);}),x:x??rect.left+35,y:y??rect.top+12});}
  install(){
    this.graph.onChange(reason=>{if(['add','remove','connect','disconnect','restore'].includes(reason))this.render();else this.refresh();this.onChange(reason);});
    this.canvas.addEventListener('pointerdown',e=>{
      let input=e.target.closest('input');if(input){this.snapshot();return;}
      this.canvas.focus();let el=e.target.closest('.graph-node'),port=e.target.closest('.port'),path=e.target.closest('[data-wire]');let p=this.toWorld(e.clientX,e.clientY);
      if(port){let id=el.dataset.id,index=Number(port.dataset.port);if(port.classList.contains('in')){if(e.altKey){let w=this.graph.wires.find(w=>w.to===id&&w.input===index);if(w)this.edit(()=>this.graph.disconnect(w.id));}return;}this.drag={kind:'wire',id,index,start:this.portPosition(id,index,true),end:p};e.preventDefault();return;}
      if(e.target.closest('.node-preview')){this.edit(()=>{let n=this.graph.nodes.find(n=>n.id===el.dataset.id);n.preview=!n.preview;this.graph.changed('preview');});return;}
      if(path){this.wireSelected=path.dataset.wire;this.selected=null;this.onSelect(null);this.drawWires();return;}
      if(el&&e.button===0){this.select(el.dataset.id);let n=this.graph.nodes.find(n=>n.id===this.selected);if(e.target.closest('.node-header')){this.snapshot();this.drag={kind:'node',n,start:p,pos:[n.x,n.y]};}return;}
      this.select(null);this.drag={kind:'pan',start:[e.clientX,e.clientY],offset:[...this.offset]};this.canvas.setPointerCapture(e.pointerId);e.preventDefault();
    });
    window.addEventListener('pointermove',e=>{if(!this.drag)return;let d=this.drag;if(d.kind==='pan'){this.offset=[d.offset[0]+e.clientX-d.start[0],d.offset[1]+e.clientY-d.start[1]];this.transform();}else if(d.kind==='node'){let p=this.toWorld(e.clientX,e.clientY);d.n.x=d.pos[0]+p[0]-d.start[0];d.n.y=d.pos[1]+p[1]-d.start[1];let el=$(`[data-id="${d.n.id}"]`,this.nodes);el.style.left=d.n.x+'px';el.style.top=d.n.y+'px';this.drawWires();}else if(d.kind==='wire'){d.end=this.toWorld(e.clientX,e.clientY);this.drawWires();}});
    window.addEventListener('pointerup',e=>{if(!this.drag)return;let d=this.drag;this.drag=null;if(d.kind==='wire'){let target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.port.in');if(target){let node=target.closest('.graph-node');this.edit(()=>this.graph.connect(d.id,d.index,node.dataset.id,Number(target.dataset.port)));}}else if(d.kind==='node')this.onChange('layout');this.drawWires();});
    this.nodes.addEventListener('input',e=>{if(!e.target.matches('input'))return;let el=e.target.closest('.graph-node'),n=this.graph.nodes.find(n=>n.id===el.dataset.id),value=Number(e.target.value);if(Number.isFinite(value)){n.params.value=clamp(value,Number(n.params.min),Number(n.params.max));n.revision++;for(let input of $$('input',el))if(input!==e.target)input.value=n.params.value;this.graph.changed('parameter');}});
    this.canvas.addEventListener('wheel',e=>{e.preventDefault();let p=this.toWorld(e.clientX,e.clientY),r=this.canvas.getBoundingClientRect();this.scale=clamp(this.scale*Math.exp(-e.deltaY*.0015),.2,2);this.offset=[e.clientX-r.left-p[0]*this.scale,e.clientY-r.top-p[1]*this.scale];this.transform();},{passive:false});
    this.canvas.addEventListener('dblclick',e=>{if(!e.target.closest('.graph-node'))this.library(e.clientX,e.clientY);});
    this.canvas.addEventListener('contextmenu',e=>{e.preventDefault();let el=e.target.closest('.graph-node');if(el){let id=el.dataset.id;menu([{label:'Toggle preview',icon:'eye',action:()=>this.edit(()=>{let n=this.graph.nodes.find(n=>n.id===id);n.preview=!n.preview;this.graph.changed('preview');})},{label:'Duplicate component',icon:'copy',action:()=>this.edit(()=>{let n=this.graph.nodes.find(n=>n.id===id);this.graph.add(n.type,n.x+30,n.y+40,structuredClone(n.params));})},null,{label:'Delete component',icon:'delete',action:()=>this.edit(()=>{this.graph.remove(id);this.select(null);})}],e.clientX,e.clientY);}else this.library(e.clientX,e.clientY);});
    this.canvas.addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();e.stopPropagation();if(this.selected)this.edit(()=>{this.graph.remove(this.selected);this.select(null);});else if(this.wireSelected)this.edit(()=>{this.graph.disconnect(this.wireSelected);this.wireSelected=null;});}if(e.key===' '){e.preventDefault();e.stopPropagation();this.library();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopPropagation();if(e.shiftKey)this.redo();else this.undo();}});
    $('#graph-fit').innerHTML=icon('fit');$('#graph-play').innerHTML=icon('pause');$('#graph-fit').onclick=()=>this.fit();$('#add-component').onclick=()=>this.library();$('#graph-play').onclick=()=>{this.graph.enabled=!this.graph.enabled;this.graph.changed('solver');};
    $('#weave-categories').innerHTML=['Params','Math','Sets','Vector','Curve','Surface','Solid','Transform','Mesh','Analysis'].map(c=>`<button data-category="${c}">${c}</button>`).join('');$('#weave-categories').onclick=e=>{let b=e.target.closest('[data-category]');if(b){let r=b.getBoundingClientRect();this.library(r.left,r.bottom+4,b.dataset.category);}};
  }
}
function format(v){if(v===undefined)return 'No data';if(typeof v==='number')return Number(v.toFixed(5)).toString();if(v?.kind==='tree')return v.branches.map(b=>'{'+b.path.join(';')+'} '+b.items.map(format).join(', ')).join('\n');if(Array.isArray(v))return v.slice(0,12).map(format).join('\n')+(v.length>12?'\n…':'');if(v?.kind)return v.kind;return String(v);}
