import {FinalRenderer} from './final-renderer.js';
import {FINAL_DEFAULTS,MATERIAL_PRESETS,renderSettings,renderCamera,compileRenderScene} from './final-scene.js';
import {loadRenderImages,filmRGBA,encodeEXR,encodeRGBE} from './final-image.js';
import {MENUS,TOOLBARS} from '../ui/commands.js';
import {escape,icon,toast} from '../ui/ui.js';
import {download} from '../core/io.js';

const STYLE=`
#final-render-launch{margin-right:8px;font-weight:650;color:var(--accent,#28766b)}
#final-render-dialog{padding:0;border:1px solid var(--border,#c6ced1);border-radius:12px;width:min(1460px,96vw);max-width:96vw;height:min(920px,94vh);max-height:94vh;background:var(--panel,#f7f8fa);color:var(--text,#283337);box-shadow:0 24px 100px #0007;overflow:hidden}
#final-render-dialog::backdrop{background:#07111788;backdrop-filter:blur(3px)}
#final-render-dialog[open]{display:flex;flex-direction:column}#final-render-dialog *{box-sizing:border-box}
.fr-header{display:flex;align-items:center;gap:16px;padding:16px 22px;border-bottom:1px solid var(--border,#d9dfe2)}.fr-header h2{font-size:20px;line-height:1.2;margin:3px 0 0;letter-spacing:-.5px}.fr-kicker{font-size:10px;font-weight:700;letter-spacing:1.8px;color:var(--muted,#78868e)}.fr-close{margin-left:auto;font-size:24px!important;line-height:1}.fr-badge{font-size:11px;padding:5px 9px;background:#367c6918;border:1px solid #367c6933;border-radius:20px;color:var(--accent,#28776b)}
.fr-toolbar{display:flex;align-items:center;gap:8px;padding:10px 16px;border-bottom:1px solid var(--border,#d9dfe2);flex-wrap:wrap}.fr-toolbar svg{width:16px;height:16px;stroke-width:1.7}.fr-toolbar button{display:inline-flex;align-items:center;gap:6px}.fr-spacer{flex:1}#final-render-dialog button,#final-render-dialog select,#final-render-dialog input{font:inherit;font-size:12px}#final-render-dialog button{padding:7px 11px;border:1px solid var(--border,#cbd4d7);border-radius:5px;background:var(--panel,#fff);color:inherit;cursor:pointer}#final-render-dialog button:hover{filter:brightness(.95)}#final-render-dialog button:disabled{opacity:.4;cursor:default}#final-render-dialog button.fr-primary{background:#2e766b;color:white;border-color:#2e766b;font-weight:650}.fr-toolbar .fr-small{padding:5px 8px}#final-render-dialog select,#final-render-dialog input{border:1px solid var(--border,#cbd4d7);padding:6px 8px;border-radius:4px;background:var(--panel,#fff);color:inherit;min-width:0;width:100%}#final-render-dialog input[type=checkbox]{width:15px;height:15px;accent-color:#367b6d}#final-render-dialog input[type=color]{height:30px;padding:3px}#final-render-dialog button:focus-visible,#final-render-dialog input:focus-visible,#final-render-dialog select:focus-visible{outline:2px solid #389781;outline-offset:2px}
.fr-body{display:flex;min-height:0;flex:1}.fr-view{display:flex;flex-direction:column;min-width:0;flex:1;background:#171d21}.fr-stage{position:relative;flex:1;min-height:0;display:flex;align-items:center;justify-content:center;overflow:auto;padding:24px;background-color:#171d21;background-image:linear-gradient(45deg,#ffffff03 25%,transparent 25%,transparent 75%,#ffffff03 75%),linear-gradient(45deg,#ffffff03 25%,transparent 25%,transparent 75%,#ffffff03 75%);background-size:24px 24px;background-position:0 0,12px 12px}.fr-stage canvas,.fr-stage img{display:block;width:auto;height:auto;max-width:100%;max-height:100%;object-fit:contain;box-shadow:0 5px 40px #0005;background:repeating-conic-gradient(#353c41 0% 25%,#2d3338 0% 50%) 50% / 24px 24px}.fr-stage.native{display:block}.fr-stage.native canvas{max-width:none;max-height:none}.fr-reference{position:absolute;pointer-events:none}.fr-empty{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;flex-direction:column;text-align:center;background:#171d21;color:#b2c0c7;gap:10px;padding:28px}.fr-empty[hidden],.fr-reference[hidden]{display:none}.fr-empty svg{width:52px;height:52px;stroke-width:1;opacity:.5}.fr-empty h3{font-size:19px;margin:8px 0 0;color:#e0e7eb}.fr-empty p{max-width:450px;font-size:13px;line-height:1.7;margin:0}.fr-imagebar{padding:8px 15px;color:#9fadb5;font-size:11px;border-top:1px solid #ffffff10;display:flex;gap:14px;flex-wrap:wrap}.fr-imagebar span:last-child{margin-left:auto}
.fr-sidebar{width:328px;min-width:270px;display:flex;flex-direction:column;border-left:1px solid var(--border,#d9dfe2);background:var(--panel,#f7f8fa)}.fr-tabs{display:flex;flex-wrap:wrap;padding:9px 10px;gap:5px;border-bottom:1px solid var(--border,#d9dfe2)}#final-render-dialog .fr-tabs button{font-size:11px;padding:5px 8px;border-color:transparent;background:transparent}.fr-tabs button.active{background:#367b6d18!important;color:var(--accent,#28766b)!important;border-color:#367b6d33!important}.fr-fields{padding:17px 18px;overflow-y:auto;flex:1;min-height:0}.fr-fields h3{font-size:14px;margin:0 0 6px}.fr-fields h4{font-size:11px;text-transform:uppercase;letter-spacing:1px;margin:22px 0 11px;color:var(--muted,#7d8b91)}.fr-fields p{font-size:11px;line-height:1.65;color:var(--muted,#73828a);margin:7px 0 15px}.fr-field{display:grid;grid-template-columns:1fr 128px;align-items:center;gap:10px;margin:9px 0;font-size:12px}.fr-check{display:flex;align-items:center;gap:8px;font-size:12px;margin:12px 0}.fr-fields .fr-row{display:flex;gap:7px;margin:12px 0}.fr-fields .fr-row>*{flex:1}.fr-note{font-size:11px;line-height:1.65;border-left:2px solid #6c9789;padding:9px 10px;background:#6197830b}.fr-light{padding:11px;border:1px solid var(--border,#d0d8dc);border-radius:6px;margin:12px 0}.fr-light h4{margin:0 0 8px}.fr-light .fr-field{grid-template-columns:1fr 110px}.fr-vec{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:8px 0}.fr-vec label{display:flex;align-items:center;gap:4px;font-size:10px}.fr-light .fr-remove{width:100%;font-size:11px!important;margin-top:8px}.fr-footer{border-top:1px solid var(--border,#d9dfe2);padding:11px 17px;display:flex;gap:12px;align-items:center;font-size:11px}.fr-footer progress{height:5px;max-width:220px;min-width:60px;flex:1;accent-color:#3c8b79}.fr-error{color:#b64235;padding:0 17px;max-height:76px;overflow:auto;font-size:12px;white-space:pre-wrap}.fr-error:empty{display:none}.fr-warning{color:#c7a36a!important}.fr-status{min-width:100px}.fr-fields details{font-size:11px;line-height:1.6;margin-top:15px}.fr-fields summary{cursor:pointer;font-weight:650}
body.dark #final-render-dialog{background:#232b30;color:#dce4e8}body.dark #final-render-dialog input,body.dark #final-render-dialog select,body.dark #final-render-dialog button,body.dark .fr-sidebar{background:#263137;color:#dce4e8;border-color:#465159}body.dark .fr-header,body.dark .fr-toolbar,body.dark .fr-tabs,body.dark .fr-footer,body.dark .fr-sidebar{border-color:#3c484f}
@media(max-width:850px){#final-render-dialog{height:96vh;max-height:96vh;width:98vw;max-width:98vw}.fr-body{flex-direction:column}.fr-view{min-height:220px;flex:1}.fr-sidebar{width:100%;min-height:240px;height:38%;border-left:0;border-top:1px solid var(--border,#d9dfe2)}.fr-fields{padding:10px 16px}.fr-tabs{flex-wrap:nowrap}.fr-tabs button{flex:1}.fr-header{padding:10px 15px}.fr-stage{padding:10px}.fr-toolbar{padding:8px;gap:5px}.fr-footer{flex-wrap:wrap}.fr-badge{display:none}}
`;
const field=(key,label,value,min,max,step='any',prefix='setting')=>`<label class="fr-field"><span>${escape(label)}</span><input type="number" data-${prefix}="${key}" value="${escape(value)}" min="${min}" max="${max}" step="${step}"></label>`;
const colorField=(key,label,value,prefix='setting')=>`<label class="fr-field"><span>${escape(label)}</span><input type="color" data-${prefix}="${key}" value="${escape(value)}"></label>`;
const selectField=(key,label,value,options,prefix='setting')=>`<label class="fr-field"><span>${escape(label)}</span><select data-${prefix}="${key}">${options.map(o=>{const [id,name]=Array.isArray(o)?o:[o,o];return `<option value="${escape(id)}" ${id===value?'selected':''}>${escape(name)}</option>`;}).join('')}</select></label>`;
const check=(key,label,value)=>`<label class="fr-check"><input type="checkbox" data-setting="${key}" ${value?'checked':''}>${escape(label)}</label>`;

export function installFinalRendering(app){
  if(app.finalRender)return app.finalRender;
  const style=document.createElement('style');style.id='final-render-style';style.textContent=STYLE;document.head.append(style);
  const root=document.createElement('dialog');root.id='final-render-dialog';root.setAttribute('aria-labelledby','fr-title');root.innerHTML=`
    <header class="fr-header"><div><div class="fr-kicker">VELDRA / FINAL RENDERING</div><h2 id="fr-title">Render studio</h2></div><span class="fr-badge">Progressive path tracing</span><button class="fr-close" data-fr="close" aria-label="Close render window">×</button></header>
    <div class="fr-toolbar"><button class="fr-primary" id="fr-start" data-fr="start">${icon('play')} Render</button><button id="fr-pause" data-fr="pause" disabled>Pause</button><button id="fr-stop" data-fr="stop" disabled>Stop</button><span class="fr-spacer"></span><select id="fr-pass" aria-label="Render pass" style="width:128px"><option value="beauty">Beauty</option><option value="albedo">Albedo</option><option value="normal">Normals</option><option value="depth">Depth</option><option value="samples">Sample count</option></select><button data-fr="zoom" class="fr-small">Fit / 1:1</button><button data-fr="store" id="fr-store" disabled>Store A</button><button data-fr="compare" id="fr-compare" disabled>Compare A</button><button data-fr="export" id="fr-export" disabled>${icon('save')} Save image</button></div>
    <div class="fr-body"><section class="fr-view"><div class="fr-stage" id="fr-stage"><canvas id="fr-canvas" width="960" height="640" aria-label="Final rendered image"></canvas><img id="fr-reference" class="fr-reference" alt="Stored comparison render" hidden><div class="fr-empty" id="fr-empty">${icon('render')}<h3>From model to final image.</h3><p>Render the active camera with real light transport, materials and soft shadows. Weave previews are included without baking.</p><button class="fr-primary" data-fr="start">Render current scene</button></div></div><div class="fr-imagebar"><span id="fr-image-info">No image rendered</span><span id="fr-stale"></span><span id="fr-backend">Automatic · WebGPU / CPU</span></div></section>
    <aside class="fr-sidebar"><nav class="fr-tabs" aria-label="Render settings">${[['render','Render'],['materials','Materials'],['lighting','Lighting'],['camera','Scene'],['output','Output']].map(([id,name])=>`<button data-fr-tab="${id}" class="${id==='render'?'active':''}">${name}</button>`).join('')}</nav><div class="fr-fields" id="fr-fields"></div></aside></div>
    <div id="fr-error" class="fr-error" role="alert"></div><footer class="fr-footer"><span class="fr-status" id="fr-status">Ready to render</span><progress id="fr-progress" value="0" max="1" aria-label="Render progress"></progress><span id="fr-samples">0 samples</span><span class="fr-spacer"></span><span id="fr-scene-stats"></span><span id="fr-time">0.0 s</span></footer>
    <input id="fr-file" type="file" hidden accept=".png,.jpg,.jpeg,.webp,.hdr">
  `;document.body.append(root);
  const $=id=>root.querySelector(id);let tab='render',materialId=null,request=0,preparing=false,lastStatus=null,reference=null,exportFormat='png';
  const settings=()=>renderSettings(app.doc.extra.finalRender??{});
  const renderer=new FinalRenderer($('#fr-canvas'),status=>{lastStatus=status;$('#fr-status').textContent={idle:'Ready',preparing:'Preparing scene',rendering:'Rendering',paused:'Paused',completed:'Completed',cancelled:'Stopped',error:'Render failed'}[status.state]??status.state;$('#fr-progress').value=status.progress;$('#fr-samples').textContent=`${status.samples} / ${renderer.settings?.samples??settings().samples} samples`;$('#fr-backend').textContent=status.backend;$('#fr-backend').title=status.fallbackReason||'';$('#fr-time').textContent=status.elapsed.toFixed(1)+' s';$('#fr-scene-stats').textContent=`${status.triangles.toLocaleString()} triangles · ${status.lights} lights`;$('#fr-pause').disabled=!['rendering','paused'].includes(status.state);$('#fr-pause').textContent=status.state==='paused'?'Resume':'Pause';$('#fr-stop').disabled=!['preparing','rendering','paused'].includes(status.state);const image=renderer.frame||renderer.device;$('#fr-export').disabled=!image;$('#fr-store').disabled=!image;if(status.errors.length)$('#fr-error').textContent=status.errors.join('\n');});
  function saveSettings(next){app.doc.transaction('Render settings',()=>app.doc.extra.finalRender=renderSettings(next));}
  function updateView(){const s=settings();renderer.setView({exposure:s.exposure,toneMap:s.toneMap,denoise:s.denoise,focusDistance:s.focusDistance,pass:$('#fr-pass').value});}
  function object(){return app.doc.get(materialId)??app.doc.selected()[0]??app.doc.objects[0];}
  function editMaterial(change){const o=object();if(!o)return;app.doc.transaction('Render material',()=>{const values={...change};if('color' in values){o.color=values.color;delete values.color;}o.material={metallic:0,roughness:.4,...o.material,...values};app.doc.touch(o);});}
  function refresh(){const s=settings(),body=$('#fr-fields');root.querySelectorAll('[data-fr-tab]').forEach(b=>b.classList.toggle('active',b.dataset.frTab===tab));
    if(tab==='render')body.innerHTML=`<h3>Image quality</h3><p>A frozen scene and camera are traced progressively. Exposure and denoising can be changed without restarting.</p>${selectField('preset','Preset','custom',[['custom','Custom'],['draft','Draft · 32 spp'],['standard','Standard · 128 spp'],['production','Production · 512 spp']],'action')}${field('width','Width (px)',s.width,16,8192,1)}${field('height','Height (px)',s.height,16,8192,1)}${field('samples','Samples per pixel',s.samples,1,65536,1)}${field('bounces','Path depth',s.bounces,1,32,1)}${field('quality','Tessellation quality',s.quality,.25,4,.25)}${selectField('backend','Engine',s.backend,[['auto','Automatic'],['webgpu','WebGPU only'],['cpu','CPU workers']])}<h4>Image development</h4>${field('exposure','Exposure (EV)',s.exposure,-16,16,.25)}${selectField('toneMap','Tone mapping',s.toneMap,[['aces','ACES fitted'],['reinhard','Reinhard'],['linear','Linear / sRGB']])}${check('denoise','Edge-aware denoising',s.denoise)}${field('fireflyClamp','Radiance clamp (0 = off)',s.fireflyClamp,0,1000000)}<div class="fr-note">Denoising is a normal-, depth- and albedo-guided spatial filter. Raw HDR and EXR exports remain unfiltered. Clamping is optional and introduces bias.</div>`;
    else if(tab==='camera')body.innerHTML=`<h3>Scene & camera</h3><p>The chosen modeling viewport supplies the camera position, projection and field of view.</p>${selectField('cameraName','Camera',s.cameraName??app.activeView,Object.keys(app.cameras))}${field('aperture',`Aperture diameter (${app.doc.units})`,s.aperture,0,1000)}${field('focusDistance',`Focus distance (${app.doc.units})`,s.focusDistance,.001,1e8)}<div class="fr-row"><button data-fr="focus">Focus on camera target</button></div><h4>Scene inclusion</h4>${check('includePreviews','Include live Weave geometry',s.includePreviews)}${check('ground','Render ground plane',s.ground)}${colorField('groundColor','Ground color',s.groundColor)}${field('groundZ','Ground elevation',s.groundZ,-1e8,1e8)}<button data-fr="ground">Place ground below model</button>${check('transparent','Transparent camera background',s.transparent)}<p>Hidden objects and hidden layers are excluded. Curves and points are construction geometry: use Pipe or create a surface to render them.</p>`;
    else if(tab==='materials'){const o=object();if(!o){body.innerHTML='<h3>Materials</h3><p>Create an object or bake Weave geometry before assigning a material.</p><button data-fr="bake">Bake Weave geometry</button>';return;}materialId=o.id;const m=o.material??{};body.innerHTML=`<h3>Surface materials</h3><p>Assignments are saved with the document and support undo. Unbaked previews retain their graph appearance.</p>${selectField('object','Object',o.id,app.doc.objects.map(o=>[o.id,o.name]),'action')}${selectField('materialPreset','Preset','custom',['custom',...Object.keys(MATERIAL_PRESETS)],'action')}${colorField('color','Base color',o.color,'material')}${field('metallic','Metallic',m.metallic??0,0,1,.05,'material')}${field('roughness','Roughness',m.roughness??.4,.025,1,.025,'material')}${field('transmission','Transmission',m.transmission??0,0,1,.05,'material')}${field('ior','Index of refraction',m.ior??1.5,1.0001,3,.01,'material')}<p>Transmission uses ideal smooth dielectric interfaces; the roughness slider affects the opaque GGX lobe, not frosted glass.</p><h4>Emission</h4>${field('emission','Emission strength',m.emission??0,0,1000000,.5,'material')}${colorField('emissionColor','Emission color',m.emissionColor??o.color,'material')}<h4>Base-color texture</h4>${selectField('pattern','Pattern',m.pattern??'none',['none','checker'],'material')}${colorField('checkerColor','Checker color',m.checkerColor??'#eeeeee','material')}${field('textureScale',`Repeat size (${app.doc.units})`,m.textureScale??1,.000001,1e6,.1,'material')}${field('textureRotation','Rotation (°)',m.textureRotation??0,-360,360,5,'material')}<div class="fr-row"><button data-fr="texture">Load image…</button><button data-fr="remove-texture">Clear image</button></div><p>${m.texture?'Embedded image assigned.':'No bitmap assigned.'} Textures use world-space box projection.</p><button data-fr="copy-material">Apply to viewport selection</button>`;}
    else if(tab==='lighting'){body.innerHTML=`<h3>Environment & lighting</h3><p>Image environments use luminance-weighted importance sampling. Rectangular lights and emissive objects participate in reflections and indirect lighting.</p>${colorField('environmentColor','Sky color',s.environmentColor)}${field('environmentStrength','Environment intensity',s.environmentStrength,0,100,.1)}${field('environmentRotation','Rotation (°)',s.environmentRotation,-360,360,5)}<div class="fr-row"><button data-fr="environment">Load HDR / image…</button><button data-fr="remove-environment">Clear</button></div><p>${s.environmentImage?'Embedded image environment active.':'Procedural studio sky active.'}</p><div class="fr-row"><button data-fr="studio">Studio rig</button><button data-fr="black">Black environment</button></div><h4>Scene lights</h4><div class="fr-row"><select id="fr-light-type" aria-label="New light type"><option value="area">Rectangle</option><option value="point">Point</option><option value="spot">Spot</option><option value="sun">Sun</option></select><button data-fr="add-light">Add light</button></div>`+s.lights.map((l,i)=>{const vec=(key,label,value)=>`<div class="fr-kicker">${label}</div><div class="fr-vec">${['X','Y','Z'].map((a,j)=>`<label>${a}<input type="number" step="any" data-light="${i}" data-light-key="${key}.${j}" value="${value?.[j]??0}" aria-label="${label} ${a}"></label>`).join('')}</div>`;return `<div class="fr-light"><h4>${escape(l.name??l.type)}</h4><label class="fr-check"><input type="checkbox" data-light="${i}" data-light-key="enabled" ${l.enabled!==false?'checked':''}>Enabled · ${escape(l.type)}</label><label class="fr-field"><span>Color</span><input type="color" data-light="${i}" data-light-key="color" value="${escape(l.color??'#ffffff')}"></label><label class="fr-field"><span>Intensity</span><input type="number" min="0" max="1000000000" step="any" data-light="${i}" data-light-key="power" value="${l.power??1}"></label>${l.type!=='sun'?vec('position','Position',l.position):''}${l.type!=='point'?vec('direction',l.type==='sun'?'Direction toward sun':'Emission direction',l.direction):''}${(l.type==='area'?['width','height']:l.type==='sun'?['angle']:l.type==='spot'?['cone']:[]).map(key=>`<label class="fr-field"><span>${key}</span><input type="number" min=".001" step="any" data-light="${i}" data-light-key="${key}" value="${l[key]??10}"></label>`).join('')}<button class="fr-remove" data-fr="remove-light" data-index="${i}">Remove light</button></div>`;}).join('');}
    else body.innerHTML=`<h3>Image output</h3><p>Save the current progressive result at its actual pixel resolution, including partially completed renders.</p>${selectField('format','File format',exportFormat,[['png','PNG · 8-bit RGBA'],['jpeg','JPEG · 8-bit RGB'],['hdr','Radiance HDR · RGBE'],['exr','OpenEXR · float AOVs']],'action')}<button class="fr-primary" data-fr="export">Save current image</button><h4>Render passes</h4><div class="fr-note">Beauty · Albedo · World normals · Camera depth · Sample count</div><p>PNG and JPEG export the selected display pass with exposure, tone mapping and optional denoising. HDR exports scene-linear beauty. EXR stores unfiltered float RGBA, albedo, normal, depth and per-pixel sample count, with no exposure or tone mapping baked in.</p><h4>Image comparison</h4><p>Store A saves the currently developed image for side-by-side-in-time comparison. Compare A toggles it over the current render.</p><h4>Rendering notes</h4><p>Final rendering is independent of viewport grid, selection outlines and control points. Settings, lights and embedded textures are stored in .veldra documents.</p><details><summary>Current scene diagnostics</summary><pre style="white-space:pre-wrap">${escape([...(lastStatus?.warnings??[]),...(lastStatus?.fallbackReason?[lastStatus.fallbackReason]:[])].join('\n')||'No warnings.')}</pre></details>`;
  }
  async function start(overrides={}){const id=++request;renderer.cancel();preparing=true;$('#fr-error').textContent='';$('#fr-status').textContent='Preparing geometry';$('#fr-stop').disabled=false;
    try{const s=renderSettings({...settings(),...overrides});saveSettings(s);const camera=renderCamera(app.cameras[s.cameraName]??app.cameras[app.activeView],s);app.graph.evaluate({document:app.doc,version:app.doc.version});app.updatePreviews();const entries=structuredClone([...app.doc.visibleObjects(),...(s.includePreviews?app.previews:[])]),images=await loadRenderImages(entries,s);if(id!==request)return;await new Promise(resolve=>setTimeout(resolve,0));if(id!==request)return;const scene=compileRenderScene(entries,s,images);$('#fr-empty').hidden=true;$('#fr-reference').hidden=true;$('#fr-stale').textContent='';$('#fr-image-info').textContent=`${s.width} × ${s.height} px · ${s.cameraName??app.activeView}`;preparing=false;await renderer.start(scene,camera,s);
    }catch(error){if(id===request){$('#fr-error').textContent=error.message;$('#fr-status').textContent='Render failed';toast(error.message,true);}}
    finally{if(id===request){preparing=false;$('#fr-stop').disabled=!['preparing','rendering','paused'].includes(renderer.state);}}
  }
  function stop(){request++;preparing=false;renderer.cancel();$('#fr-stop').disabled=true;}
  function show(nextTab=tab){tab=nextTab;if(!root.open)root.showModal();refresh();}
  async function developedCanvas(){const frame=await renderer.snapshot(),canvas=document.createElement('canvas');canvas.width=frame.width;canvas.height=frame.height;canvas.getContext('2d').putImageData(new ImageData(filmRGBA(frame,{...renderer.view,transparent:renderer.settings.transparent}),frame.width,frame.height),0,0);return canvas;}
  async function exportImage(format=exportFormat){const suffix=(renderer.view?.pass??'beauty'),name=`${app.doc.name}-${suffix}`;if(format==='exr'||format==='hdr'){const frame=await renderer.snapshot(),blob=format==='exr'?encodeEXR(frame,{renderer:renderer.backend,samples:renderer.sample,transparent:renderer.settings.transparent,camera:renderer.camera}):encodeRGBE(frame);download(blob,`${app.doc.name}.${format}`);return;}const canvas=await developedCanvas();if(format==='jpeg'){const ctx=canvas.getContext('2d');ctx.globalCompositeOperation='destination-over';ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);}const blob=await new Promise(resolve=>canvas.toBlob(resolve,format==='jpeg'?'image/jpeg':'image/png',.95));if(!blob)throw Error('Image encoder failed');download(blob,`${name}.${format==='jpeg'?'jpg':'png'}`);}
  function chooseImage(kind){$('#fr-file').dataset.kind=kind;$('#fr-file').click();}
  $('#fr-file').onchange=async e=>{const file=e.target.files[0],kind=e.target.dataset.kind;e.target.value='';if(!file)return;try{if(file.size>32*1024*1024)throw Error('Choose an image below 32 MiB');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Unable to read image'));reader.readAsDataURL(file);});let source=String(data);if(file.name.toLowerCase().endsWith('.hdr'))source=source.replace(/^data:[^;,]*/, 'data:image/vnd.radiance');await loadRenderImages(kind==='texture'?[{material:{texture:source}}]:[],{environmentImage:kind==='environment'?source:''});if(kind==='environment')saveSettings({...settings(),environmentImage:source});else editMaterial({texture:source});refresh();}catch(error){$('#fr-error').textContent=error.message;}};
  root.addEventListener('change',e=>{const t=e.target;try{
    if(t.id==='fr-pass'){renderer.setView({pass:t.value});return;}
    if(t.dataset.setting){const key=t.dataset.setting,value=t.type==='checkbox'?t.checked:t.type==='number'?Number(t.value):t.value;if(t.type==='number'&&!Number.isFinite(value))throw Error('Enter a finite number');saveSettings({...settings(),[key]:value});if(['exposure','toneMap','denoise'].includes(key))updateView();return;}
    if(t.dataset.material){const value=t.type==='number'?Number(t.value):t.value;if(t.type==='number'&&(!Number.isFinite(value)||!t.checkValidity()))throw Error('Material value is outside its allowed range');editMaterial({[t.dataset.material]:value});return;}
    if(t.dataset.light!==undefined){const s=settings(),l=s.lights[Number(t.dataset.light)],[key,axis]=t.dataset.lightKey.split('.'),value=t.type==='checkbox'?t.checked:t.type==='number'?Number(t.value):t.value;if(t.type==='number'&&!Number.isFinite(value))throw Error('Enter a finite light value');if(axis!==undefined){l[key]??=[0,0,0];l[key][Number(axis)]=value;}else l[key]=value;saveSettings(s);return;}
    const action=t.dataset.action;if(action==='object'){materialId=t.value;refresh();}else if(action==='materialPreset'){if(MATERIAL_PRESETS[t.value])editMaterial(MATERIAL_PRESETS[t.value]);refresh();}else if(action==='format'){exportFormat=t.value;}else if(action==='preset'){const presets={draft:{width:640,height:426,samples:32,bounces:4,quality:1},standard:{width:1200,height:800,samples:128,bounces:8,quality:1.5},production:{width:1920,height:1080,samples:512,bounces:12,quality:2}};if(presets[t.value])saveSettings({...settings(),...presets[t.value]});refresh();}
  }catch(error){$('#fr-error').textContent=error.message;}});
  root.addEventListener('click',async e=>{const t=e.target.closest('[data-fr],[data-fr-tab]');if(!t)return;try{if(t.dataset.frTab){tab=t.dataset.frTab;refresh();return;}const action=t.dataset.fr;
    if(action==='start')await start();else if(action==='close'){stop();root.close();}else if(action==='stop')stop();else if(action==='pause'){renderer.state==='paused'?renderer.resume():renderer.pause();}else if(action==='zoom')$('#fr-stage').classList.toggle('native');else if(action==='export')await exportImage();
    else if(action==='store'){const canvas=await developedCanvas();reference=canvas.toDataURL('image/png');$('#fr-reference').src=reference;$('#fr-compare').disabled=false;}
    else if(action==='compare'){if(reference){$('#fr-reference').hidden=!$('#fr-reference').hidden;t.textContent=$('#fr-reference').hidden?'Compare A':'Showing A';}}
    else if(action==='focus'){const c=app.cameras[settings().cameraName]??app.cameras[app.activeView];saveSettings({...settings(),focusDistance:c.radius});refresh();}
    else if(action==='ground'){saveSettings({...settings(),groundZ:app.doc.bounds().min[2]-.001});refresh();}
    else if(action==='texture'||action==='environment')chooseImage(action);
    else if(action==='remove-texture'){editMaterial({texture:''});refresh();}else if(action==='remove-environment'){saveSettings({...settings(),environmentImage:''});refresh();}
    else if(action==='black'){saveSettings({...settings(),environmentStrength:0});refresh();}
    else if(action==='studio'){saveSettings({...settings(),environmentStrength:.35,environmentImage:'',lights:[{type:'area',name:'Key softbox',position:[-12,-12,24],direction:[.4,.4,-1],width:12,height:10,color:'#fff0de',power:10},{type:'area',name:'Fill softbox',position:[15,4,16],direction:[-1,-.3,-1],width:8,height:12,color:'#dcecff',power:5}]});refresh();}
    else if(action==='add-light'){const s=settings();if(s.lights.length>=64)throw Error('Maximum 64 user lights');const type=$('#fr-light-type').value;s.lights.push({type,name:`${type} ${s.lights.length+1}`,color:'#ffffff',power:type==='area'?8:type==='sun'?3:800,position:[-10,-10,20],direction:type==='sun'?[-1,-1,2]:[0,0,-1],width:10,height:10,angle:3,cone:45});saveSettings(s);refresh();}
    else if(action==='remove-light'){const s=settings();s.lights.splice(Number(t.dataset.index),1);saveSettings(s);refresh();}
    else if(action==='bake'){app.bake();refresh();}else if(action==='copy-material'){const source=object(),selected=app.doc.selected();if(!source||!selected.length)throw Error('Select target objects in the modeling viewport first.');app.doc.transaction('Assign render material to selection',()=>{for(const o of selected){o.color=source.color;o.material=structuredClone(source.material);app.doc.touch(o);}});refresh();}
  }catch(error){$('#fr-error').textContent=error.message;}});
  root.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='F9'||(e.key==='Enter'&&(e.ctrlKey||e.metaKey))){e.preventDefault();void start();}});root.addEventListener('cancel',e=>{e.preventDefault();stop();root.close();});
  const commands=()=>{for(const [id,label,fn] of [['render','Render final image',()=>{show();return start();}],['renderwindow','Open render window',()=>show()],['rendersettings','Final render settings',()=>show('render')],['rendermaterials','Render materials',()=>show('materials')],['renderlights','Render lighting and environment',()=>show('lighting')],['rendercancel','Cancel final render',stop],['renderpng','Export final PNG',()=>exportImage('png')],['renderexr','Export multilayer EXR',()=>exportImage('exr')],['renderhdr','Export linear HDR',()=>exportImage('hdr')]])app.commands.add(id,label,'Render','render',fn,id==='render'?'F9':'');};commands();
  MENUS.Render=['render','renderwindow','rendercancel',null,'rendersettings','rendermaterials','renderlights',null,'renderpng','renderexr','renderhdr'];TOOLBARS.Render=['render','renderwindow','rendercancel',null,'rendersettings','rendermaterials','renderlights',null,'renderpng','renderexr','renderhdr'];
  const menuButton=document.createElement('button');menuButton.dataset.menu='Render';menuButton.textContent='Render';document.querySelector('#menubar').insertBefore(menuButton,document.querySelector('[data-menu="Help"]'));const toolbar=document.createElement('button');toolbar.dataset.tab='Render';toolbar.textContent='Render';document.querySelector('#ribbon-tabs').append(toolbar);
  const launch=document.createElement('button');launch.id='final-render-launch';launch.className='workspace-switch';launch.dataset.command='renderwindow';launch.textContent='Render';document.querySelector('.titlebar-right').prepend(launch);
  app.doc.onChange(reason=>{if(!app.commands.items.has('render'))commands();if(reason!=='selection'&&(renderer.frame||renderer.device)){$('#fr-stale').textContent='Scene/settings changed · render again to update';$('#fr-stale').className='fr-warning';}if(root.open&&!root.contains(document.activeElement))refresh();});
  document.addEventListener('keydown',e=>{if(e.key==='F9'&&!root.open){e.preventDefault();show();void start();}});
  const updateInspector=app.updateInspector.bind(app);app.updateInspector=(...args)=>{updateInspector(...args);if(app.panel==='materials'){const content=document.querySelector('#inspector-content');if(content&&!content.querySelector('[data-command="rendermaterials"]')){const button=document.createElement('button');button.dataset.command='rendermaterials';button.className='secondary';button.style.cssText='margin:12px 18px';button.textContent='Final render materials & textures…';content.append(button);}}};
  refresh();app.finalRender={renderer,show,start,stop,exportImage,refresh,get settings(){return settings();},setSettings:saveSettings,get preparing(){return preparing;}};return app.finalRender;
}
function connectFinalRendering(){if(typeof window==='undefined'||typeof document==='undefined')return;let tries=0;const connect=()=>{if(window.veldra?.ready){installFinalRendering(window.veldra);return;}if(++tries<600)setTimeout(connect,100);};connect();}
connectFinalRendering();
