import {SoftwareRenderer} from './software.js';
import {M,V,hexRGB} from '../core/math.js';
import {RASTER_WGSL,SURFACE_COMPUTE_WGSL,GL_VERTEX,GL_FRAGMENT,GL_LINE_VERTEX,GL_LINE_FRAGMENT} from './shaders.js';
export class Renderer{
  constructor(canvas){this.canvas=canvas;this.backend='initializing';this.errors=[];this.stats={triangles:0,vertices:0,drawCalls:0,frameMs:0};this.mode=0;this.grid=true;this.showEdges=true;this.clip=[0,0,1,0];this.clipOn=false;this.exposure=1;this.dirty=true;this.shadowDirty=true;this.buffers=[];this.lightVP=M.mul(M.ortho(-45,45,-45,45,.1,200),M.lookAt([-42,-55,70],[0,0,0],[0,0,1]));}
  async init(){try{if(!navigator.gpu)throw Error('WebGPU is unavailable in this browser');let adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!adapter)throw Error('No WebGPU adapter');this.adapterInfo=adapter.info;this.device=await adapter.requestDevice();this.device.addEventListener('uncapturederror',e=>{this.errors.push(e.error.message);console.error('WebGPU:',e.error.message);});this.device.lost.then(info=>{this.errors.push('GPU device lost: '+info.message);this.onError?.('GPU device lost. Save the document and reload to reinitialize graphics.');});await this.initGPU();this.backend='WebGPU';}catch(e){this.fallbackReason=e.message;console.warn('Veldra renderer:',e.message);if(this.context){let replacement=this.canvas.cloneNode();this.canvas.replaceWith(replacement);this.canvas=replacement;}try{this.initGL();this.backend='WebGL2 fallback';}catch(glError){this.fallbackReason+='; '+glError.message;if(this.gl){let replacement=this.canvas.cloneNode();this.canvas.replaceWith(replacement);this.canvas=replacement;this.gl=null;}this.software=new SoftwareRenderer(this.canvas);this.backend='Software fallback';}}return this;}
  async initGPU(){
    let d=this.device;d.pushErrorScope('validation');this.format=navigator.gpu.getPreferredCanvasFormat();let module=d.createShaderModule({code:RASTER_WGSL,label:'Veldra physically based raster shaders'}),info=await module.getCompilationInfo();let errors=info.messages.filter(m=>m.type==='error');if(errors.length)throw Error(errors.map(m=>m.message).join('; '));
    this.layout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}},{binding:1,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'depth'}},{binding:2,visibility:GPUShaderStage.FRAGMENT,sampler:{type:'comparison'}}]});let layout=d.createPipelineLayout({bindGroupLayouts:[this.layout]});
    const vertex={module,entryPoint:'vs',buffers:[{arrayStride:48,attributes:[{shaderLocation:0,offset:0,format:'float32x3'},{shaderLocation:1,offset:12,format:'float32x3'},{shaderLocation:2,offset:24,format:'float32x4'},{shaderLocation:3,offset:40,format:'float32x2'}]}]},depth={format:'depth24plus',depthWriteEnabled:true,depthCompare:'less-equal'};
    this.solidPipeline=d.createRenderPipeline({label:'Shaded PBR',layout,vertex,fragment:{module,entryPoint:'fs',targets:[{format:this.format}]},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:depth,multisample:{count:4}});
    this.gridPipeline=d.createRenderPipeline({label:'Analytic construction grid',layout,vertex,fragment:{module,entryPoint:'gridFS',targets:[{format:this.format}]},primitive:{topology:'triangle-list'},depthStencil:depth,multisample:{count:4}});
    this.linePipeline=d.createRenderPipeline({label:'Depth-tested curves and edges',layout,vertex:{module,entryPoint:'lineVS',buffers:[{arrayStride:28,attributes:[{shaderLocation:0,offset:0,format:'float32x3'},{shaderLocation:1,offset:12,format:'float32x4'}]}]},fragment:{module,entryPoint:'lineFS',targets:[{format:this.format,blend:{color:{srcFactor:'src-alpha',dstFactor:'one-minus-src-alpha'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha'}}}]},primitive:{topology:'line-list'},depthStencil:{...depth,depthWriteEnabled:false},multisample:{count:4}});
    this.shadowLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.VERTEX,buffer:{type:'uniform'}}]});this.shadowPipeline=d.createRenderPipeline({label:'Directional shadow map',layout:d.createPipelineLayout({bindGroupLayouts:[this.shadowLayout]}),vertex:{...vertex,entryPoint:'shadowVS'},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less',depthBias:2,depthBiasSlopeScale:2}});
    this.shadowTexture=d.createTexture({size:[2048,2048],format:'depth32float',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING});this.shadowView=this.shadowTexture.createView();this.shadowSampler=d.createSampler({compare:'less-equal',magFilter:'linear',minFilter:'linear'});this.uniforms=[];this.bindGroups=[];
    for(let i=0;i<4;i++){let b=d.createBuffer({size:176,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});this.uniforms.push(b);this.bindGroups.push(d.createBindGroup({layout:this.layout,entries:[{binding:0,resource:{buffer:b}},{binding:1,resource:this.shadowView},{binding:2,resource:this.shadowSampler}]}));}
    this.shadowBindGroup=d.createBindGroup({layout:this.shadowLayout,entries:[{binding:0,resource:{buffer:this.uniforms[0]}}]});let ground=[];for(let p of [[-180,-180,-.025],[180,-180,-.025],[180,180,-.025],[-180,-180,-.025],[180,180,-.025],[-180,180,-.025]])ground.push(...p,0,0,1,.92,.93,.94,1,.8,0);this.groundBuffer=this.gpuBuffer(new Float32Array(ground),GPUBufferUsage.VERTEX);
    let validation=await d.popErrorScope();if(validation)throw Error(validation.message);this.context=this.canvas.getContext('webgpu');this.context.configure({device:d,format:this.format,alphaMode:'opaque'});
  }
  gpuBuffer(data,usage){let b=this.device.createBuffer({size:Math.max(4,(data.byteLength+3)&~3),usage:usage|GPUBufferUsage.COPY_DST});if(data.byteLength)this.device.queue.writeBuffer(b,0,data);return b;}
  initGL(){let gl=this.gl=this.canvas.getContext('webgl2',{antialias:true,alpha:false,preserveDrawingBuffer:true});if(!gl)throw Error('Neither WebGPU nor WebGL2 could initialize');let program=(vs,fs)=>{let p=gl.createProgram();for(let [type,src] of [[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;};this.glSolid=program(GL_VERTEX,GL_FRAGMENT);this.glLine=program(GL_LINE_VERTEX,GL_LINE_FRAGMENT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.disable(gl.CULL_FACE);}
  resize(){let ratio=(this.software?Math.min(1,1100/Math.max(1,this.canvas.clientWidth)):Math.min(devicePixelRatio||1,2)),w=Math.max(1,Math.round(this.canvas.clientWidth*ratio)),h=Math.max(1,Math.round(this.canvas.clientHeight*ratio));this.ratio=ratio;if(this.canvas.width===w&&this.canvas.height===h)return false;this.canvas.width=w;this.canvas.height=h;if(this.device&&this.backend==='WebGPU'){this.msaa?.destroy();this.depth?.destroy();this.msaa=this.device.createTexture({size:[w,h],sampleCount:4,format:this.format,usage:GPUTextureUsage.RENDER_ATTACHMENT});this.depth=this.device.createTexture({size:[w,h],sampleCount:4,format:'depth24plus',usage:GPUTextureUsage.RENDER_ATTACHMENT});}this.dirty=true;return true;}
  setScene(entries,selection=new Set()){
    const signature=JSON.stringify(entries.map(({object:o,display:d})=>[o.id,d.key,o.color,o.material,selection.has(o.id)]));if(signature===this.sceneSignature)return;this.sceneSignature=signature;
    let vert=[],indices=[],edgeData=[],curveData=[],count=0;
    const addLine=(target,e,c)=>{for(let p of e)target.push(...p,...c);};
    for(let {object:o,display:d} of entries){let selected=selection.has(o.id),color=selected?[.98,.65,.15]:hexRGB(o.color??'#72a395'),alpha=1,rough=o.material?.roughness??.4,metal=o.material?.metallic??.12;
      if(d.mesh){let m=d.mesh,base=vert.length/12;for(let i=0;i<m.positions.length;i++)vert.push(...m.positions[i],...(m.normals[i]??[0,0,1]),...color,alpha,rough,metal);for(let index of m.indices)indices.push(index+base);count+=m.indices.length/3;}
      let ec=selected?[.95,.52,.05,1]:o.preview?[.18,.38,.35,.55]:[.20,.29,.32,.46];for(let e of d.edges)addLine(edgeData,e,ec);for(let e of d.lines)addLine(curveData,e,selected?[.95,.52,.05,1]:[...color,1]);
    }
    this.vertices=new Float32Array(vert);this.indices=new Uint32Array(indices);this.edges=new Float32Array(edgeData);this.curves=new Float32Array(curveData);this.stats.triangles=count;this.stats.vertices=vert.length/12;
    if(this.backend==='WebGPU'){for(let b of this.buffers)b.destroy();let U=GPUBufferUsage;this.vertexBuffer=this.gpuBuffer(this.vertices,U.VERTEX);this.indexBuffer=this.gpuBuffer(this.indices,U.INDEX);this.edgeBuffer=this.gpuBuffer(this.edges,U.VERTEX);this.curveBuffer=this.gpuBuffer(this.curves,U.VERTEX);this.buffers=[this.vertexBuffer,this.indexBuffer,this.edgeBuffer,this.curveBuffer];}
    else if(this.gl){let gl=this.gl;for(let b of this.buffers)gl.deleteBuffer(b);const buf=(data,target)=>{let b=gl.createBuffer();gl.bindBuffer(target,b);gl.bufferData(target,data,gl.STATIC_DRAW);this.buffers.push(b);return b;};this.buffers=[];this.vertexBuffer=buf(this.vertices,gl.ARRAY_BUFFER);this.indexBuffer=buf(this.indices,gl.ELEMENT_ARRAY_BUFFER);this.edgeBuffer=buf(this.edges,gl.ARRAY_BUFFER);this.curveBuffer=buf(this.curves,gl.ARRAY_BUFFER);let grid=[];for(let i=-100;i<=100;i++){let c=i===0?[.63,.36,.36,.7]:i%5===0?[.74,.78,.8,.7]:[.82,.85,.87,.5];addLine(grid,[[-100,i,-.03],[100,i,-.03]],c);addLine(grid,[[i,-100,-.03],[i,100,-.03]],i===0?[.34,.55,.43,.7]:c);}this.gridData=new Float32Array(grid);this.gridGL=buf(this.gridData,gl.ARRAY_BUFFER);}
    this.shadowDirty=true;this.dirty=true;
  }
  render(viewports){this.resize();if(!this.vertices)return;let state=JSON.stringify([this.canvas.width,this.canvas.height,this.mode,this.grid,this.showEdges,this.clipOn,this.clip,this.exposure,viewports.map(v=>[v.x,v.y,v.width,v.height,v.camera.type,v.camera.radius,v.camera.scale,v.camera.yaw,v.camera.pitch,v.camera.target])]);if(!this.dirty&&state===this.frameState)return;this.frameState=state;let start=performance.now();this.stats.drawCalls=0;if(this.backend==='WebGPU')this.renderGPU(viewports);else if(this.software)this.software.render(this,viewports);else this.renderGL(viewports);this.stats.frameMs=performance.now()-start;this.dirty=false;}
  renderGPU(viewports){let d=this.device;if(!this.msaa){this.canvas.width=0;this.resize();}for(let i=0;i<viewports.length;i++){let v=viewports[i],g=new Float32Array(44);g.set(v.camera.matrix(v.width/v.height));g.set(this.lightVP,16);g.set([...v.camera.eye,1],32);g.set([this.mode,this.exposure,0,+this.clipOn],36);g.set(this.clip,40);d.queue.writeBuffer(this.uniforms[i],0,g);}
    let encoder=d.createCommandEncoder();if(this.shadowDirty){let pass=encoder.beginRenderPass({colorAttachments:[],depthStencilAttachment:{view:this.shadowView,depthClearValue:1,depthLoadOp:'clear',depthStoreOp:'store'}});pass.setPipeline(this.shadowPipeline);pass.setBindGroup(0,this.shadowBindGroup);pass.setVertexBuffer(0,this.vertexBuffer);pass.setIndexBuffer(this.indexBuffer,'uint32');if(this.indices.length)pass.drawIndexed(this.indices.length);pass.end();this.shadowDirty=false;this.stats.drawCalls++;}
    let pass=encoder.beginRenderPass({colorAttachments:[{view:this.msaa.createView(),resolveTarget:this.context.getCurrentTexture().createView(),clearValue:{r:.925,g:.937,b:.945,a:1},loadOp:'clear',storeOp:'discard'}],depthStencilAttachment:{view:this.depth.createView(),depthClearValue:1,depthLoadOp:'clear',depthStoreOp:'discard'}});
    for(let i=0;i<viewports.length;i++){let v=viewports[i],x=Math.floor(v.x*this.ratio),y=Math.floor(v.y*this.ratio),w=Math.min(this.canvas.width-x,Math.floor(v.width*this.ratio)),h=Math.min(this.canvas.height-y,Math.floor(v.height*this.ratio));if(w<1||h<1)continue;pass.setViewport(x,y,w,h,0,1);pass.setScissorRect(x,y,w,h);pass.setBindGroup(0,this.bindGroups[i]);
      if(this.grid){pass.setPipeline(this.gridPipeline);pass.setVertexBuffer(0,this.groundBuffer);pass.draw(6);this.stats.drawCalls++;}
      if(this.mode!==1&&this.indices.length){pass.setPipeline(this.solidPipeline);pass.setVertexBuffer(0,this.vertexBuffer);pass.setIndexBuffer(this.indexBuffer,'uint32');pass.drawIndexed(this.indices.length);this.stats.drawCalls++;}
      pass.setPipeline(this.linePipeline);if((this.showEdges||this.mode===1)&&this.edges.length){pass.setVertexBuffer(0,this.edgeBuffer);pass.draw(this.edges.length/7);this.stats.drawCalls++;}if(this.curves.length){pass.setVertexBuffer(0,this.curveBuffer);pass.draw(this.curves.length/7);this.stats.drawCalls++;}
    }pass.end();d.queue.submit([encoder.finish()]);
  }
  renderGL(viewports){let gl=this.gl;gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.disable(gl.SCISSOR_TEST);gl.clearColor(.925,.937,.945,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.SCISSOR_TEST);
    const globals=(p,camera,v)=>{gl.useProgram(p);gl.uniformMatrix4fv(gl.getUniformLocation(p,'viewProj'),false,new Float32Array(camera.matrix(v.width/v.height)));gl.uniform4fv(gl.getUniformLocation(p,'clipPlane'),this.clip);gl.uniform1i(gl.getUniformLocation(p,'clipOn'),this.clipOn);};
    const lines=(buffer,count,p)=>{if(!count)return;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,28,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,4,gl.FLOAT,false,28,12);gl.disableVertexAttribArray(2);gl.disableVertexAttribArray(3);gl.drawArrays(gl.LINES,0,count);this.stats.drawCalls++;};
    for(let v of viewports){let x=Math.floor(v.x*this.ratio),y=Math.floor(this.canvas.height-(v.y+v.height)*this.ratio),w=Math.floor(v.width*this.ratio),h=Math.floor(v.height*this.ratio);gl.viewport(x,y,w,h);gl.scissor(x,y,w,h);if(this.mode!==1&&this.indices.length){globals(this.glSolid,v.camera,v);gl.uniform3fv(gl.getUniformLocation(this.glSolid,'eye'),v.camera.eye);gl.uniform1f(gl.getUniformLocation(this.glSolid,'mode'),this.mode);gl.bindBuffer(gl.ARRAY_BUFFER,this.vertexBuffer);for(let [i,size,offset] of [[0,3,0],[1,3,12],[2,4,24],[3,2,40]]){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,size,gl.FLOAT,false,48,offset);}gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.indexBuffer);gl.drawElements(gl.TRIANGLES,this.indices.length,gl.UNSIGNED_INT,0);this.stats.drawCalls++;}globals(this.glLine,v.camera,v);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);if(this.grid)lines(this.gridGL,this.gridData.length/7);if(this.showEdges||this.mode===1)lines(this.edgeBuffer,this.edges.length/7);lines(this.curveBuffer,this.curves.length/7);gl.disable(gl.BLEND);}
  }
  async computeSurface(surface,su=48,sv=32){
    if(this.backend!=='WebGPU')throw Error('GPU surface evaluation requires WebGPU');if(surface.degreeU>7||surface.degreeV>7||surface.points.length>64||surface.points[0].length>64)throw Error('GPU evaluator limit: degree 7, 64 × 64 controls');if(!Number.isInteger(su)||!Number.isInteger(sv)||su<1||sv<1||su>2048||sv>2048)throw Error('Invalid sampling resolution');let d=this.device;
    if(!this.computePipeline){let module=d.createShaderModule({code:SURFACE_COMPUTE_WGSL}),info=await module.getCompilationInfo();if(info.messages.some(m=>m.type==='error'))throw Error(info.messages.map(m=>m.message).join(';'));this.computePipeline=d.createComputePipeline({layout:'auto',compute:{module,entryPoint:'main'}});}
    let points=[];for(let j=0;j<surface.points.length;j++)for(let i=0;i<surface.points[j].length;i++){let p=surface.points[j][i],w=surface.weights?.[j]?.[i]??1;points.push(p[0]*w,p[1]*w,p[2]*w,w);}let U=GPUBufferUsage,params=this.gpuBuffer(new Uint32Array([surface.points[0].length,surface.points.length,surface.degreeU,surface.degreeV,su,sv,surface.knotsU.length,surface.knotsV.length]),U.UNIFORM),cp=this.gpuBuffer(new Float32Array(points),U.STORAGE),knots=this.gpuBuffer(new Float32Array([...surface.knotsU,...surface.knotsV]),U.STORAGE),bytes=(su+1)*(sv+1)*16,result=d.createBuffer({size:bytes,usage:U.STORAGE|U.COPY_SRC}),read=d.createBuffer({size:bytes,usage:U.MAP_READ|U.COPY_DST});
    try{let group=d.createBindGroup({layout:this.computePipeline.getBindGroupLayout(0),entries:[params,cp,knots,result].map((buffer,binding)=>({binding,resource:{buffer}}))}),encoder=d.createCommandEncoder(),pass=encoder.beginComputePass();pass.setPipeline(this.computePipeline);pass.setBindGroup(0,group);pass.dispatchWorkgroups(Math.ceil((su+1)*(sv+1)/64));pass.end();encoder.copyBufferToBuffer(result,0,read,0,bytes);d.queue.submit([encoder.finish()]);await read.mapAsync(GPUMapMode.READ);let data=new Float32Array(read.getMappedRange()).slice();read.unmap();return data;}finally{for(let b of [params,cp,knots,result,read])b.destroy();}
  }
}
