import {V,M,clamp} from './math.js';
import {NurbsCurve,NurbsSurface,circleCurve,interpolateCurve,polyline,rectangle,loftSurface,extrudeSurface,revolveSurface,sweepSurface,transformGeometry,geometryMesh,canopySurface,canopyRibs} from './geometry.js';
import {analyzeMesh,mergeMeshes,subdivideMesh,sectionMesh} from './mesh.js';
import {booleanMesh} from './csg.js';
import {DataTree} from './graph.js';
const port=(name,type,key,def,access='item')=>({name,type,key,default:def,access});
const output=(name,type)=>({name,type});
const N=(name,key,def)=>port(name,'number',key,def);
const G=(name,key)=>port(name,'geometry',key);
const positive=(...values)=>{if(values.some(v=>!Number.isFinite(v)||v<=0))throw Error('Dimensions must be positive finite numbers');};
export const COMPONENTS={};
function define(id,name,category,inputs,outputs,run,extra={}){COMPONENTS[id]={name,category,inputs,outputs,run,...extra};}
define('number','Number slider','Params',[],[output('Value','number')],(_,p)=>[Number(p.value)],{defaults:{value:10,min:0,max:30,step:.1}});
define('panel','Panel','Params',[port('Data','any','data','Connect a wire to inspect data','list')],[output('Data','any')],([v])=>[v],{treeAware:true});
define('point','Construct point','Vector',[N('X','x',0),N('Y','y',0),N('Z','z',0)],[output('Point','point')],([x,y,z])=>[[x,y,z]]);
define('vector','Vector XYZ','Vector',[N('X','x',0),N('Y','y',0),N('Z','z',1)],[output('Vector','vector')],([x,y,z])=>[[x,y,z]]);
define('unitz','Unit Z','Vector',[N('Factor','factor',1)],[output('Vector','vector')],([v])=>[[0,0,v]]);
define('distance','Distance','Vector',[port('A','point','a',[0,0,0]),port('B','point','b',[1,0,0])],[output('Distance','number')],([a,b])=>[V.distance(a,b)]);
for(let [id,name,fn,defaults] of [['add','Addition',(a,b)=>a+b,[0,1]],['subtract','Subtraction',(a,b)=>a-b,[0,1]],['multiply','Multiply',(a,b)=>a*b,[1,2]],['divide','Division',(a,b)=>{if(Math.abs(b)<1e-15)throw Error('Division by zero');return a/b;},[1,2]],['power','Power',(a,b)=>a**b,[2,2]]])define(id,name,'Math',[N('A','a',defaults[0]),N('B','b',defaults[1])],[output('Result','number')],([a,b])=>{let v=fn(a,b);if(!Number.isFinite(v))throw Error('Non-finite result');return [v];});
for(let [id,name,fn] of [['sin','Sine',Math.sin],['cos','Cosine',Math.cos],['abs','Absolute',Math.abs],['sqrt','Square root',Math.sqrt]])define(id,name,'Math',[N('Value','value',0)],[output('Result','number')],([a])=>{let v=fn(a);if(!Number.isFinite(v))throw Error('Outside function domain');return [v];});
define('remap','Remap numbers','Math',[N('Value','value',.5),N('Source min','smin',0),N('Source max','smax',1),N('Target min','tmin',0),N('Target max','tmax',10)],[output('Value','number')],([v,a,b,c,d])=>{if(a===b)throw Error('Source domain has zero length');return [c+(v-a)/(b-a)*(d-c)];});
define('series','Series','Sets',[N('Start','start',0),N('Step','step',1),N('Count','count',10)],[output('Values','list')],([start,step,count])=>[Array.from({length:clamp(Math.floor(count),0,10000)},(_,i)=>start+i*step)]);
define('range','Range','Sets',[N('Start','start',0),N('End','end',1),N('Steps','count',10)],[output('Values','list')],([a,b,n])=>{n=clamp(Math.round(n),1,10000);return [Array.from({length:n+1},(_,i)=>a+(b-a)*i/n)];});
define('item','List item','Sets',[port('List','any','list',[],'list'),N('Index','index',0)],[output('Item','any')],([a,i])=>{a=Array.isArray(a)?a:[a];if(!a.length)throw Error('Empty list');return [a[((Math.floor(i)%a.length)+a.length)%a.length]];});
define('reverse','Reverse list','Sets',[port('List','any','list',[],'list')],[output('List','list')],([a])=>[Array.isArray(a)?[...a].reverse():[a]]);
define('merge','Merge','Sets',[port('A','any','a',[],'list'),port('B','any','b',[],'list')],[output('List','list')],([a,b])=>[[...([a].flat()),...([b].flat())]]);
define('partition','Partition list','Sets',[port('List','any','list',[],'list'),N('Size','size',4)],[output('Tree','tree')],([a,n])=>{n=clamp(Math.floor(n),1,10000);a=Array.isArray(a)?a:[a];let branches=[];for(let i=0;i<a.length;i+=n)branches.push({path:[0,i/n],items:a.slice(i,i+n)});return [new DataTree(branches)];});
for(let [id,name,method] of [['flatten','Flatten tree','flatten'],['graft','Graft tree','graft'],['simplify','Simplify tree','simplify']])define(id,name,'Sets',[port('Data','any','data',[],'tree')],[output('Tree','tree')],([a])=>[DataTree.from(a)[method]()],{treeAware:true});
define('circle','Circle','Curve',[port('Center','point','center',[0,0,0]),N('Radius','radius',5)],[output('Curve','curve')],([p,r])=>[circleCurve(p,r).toJSON()],{preview:true});
define('rectangle','Rectangle','Curve',[N('Width','width',10),N('Depth','depth',6)],[output('Curve','curve')],([w,h])=>[rectangle(w,h)],{preview:true});
define('line','Line','Curve',[port('Start','point','start',[0,0,0]),port('End','point','end',[5,0,0])],[output('Curve','curve')],([a,b])=>[polyline([a,b])],{preview:true});
define('interpolate','Interpolate curve','Curve',[port('Points','any','points',undefined,'list'),N('Degree','degree',3)],[output('Curve','curve')],([p,d])=>[interpolateCurve(p,clamp(Math.round(d),1,7)).toJSON()],{preview:true});
define('controlcurve','Control-point curve','Curve',[port('Points','any','points',undefined,'list'),N('Degree','degree',3)],[output('Curve','curve')],([p,d])=>[new NurbsCurve(p,Math.min(clamp(Math.round(d),1,7),p.length-1)).toJSON()],{preview:true});
define('dividecurve','Divide curve','Curve',[port('Curve','curve','curve'),N('Count','count',12)],[output('Points','list'),output('Tangents','list')],([g,n])=>{n=clamp(Math.round(n),1,5000);let c=NurbsCurve.from(g);return [c.sample(n),Array.from({length:n+1},(_,i)=>V.unit(c.derivative(i/n)))];});
define('curvelength','Curve length','Curve',[port('Curve','curve','curve')],[output('Length','number')],([g])=>[NurbsCurve.from(g).length(.0001)]);
define('evaluatecurve','Evaluate curve','Curve',[port('Curve','curve','curve'),N('Parameter','t',.5)],[output('Point','point'),output('Tangent','vector'),output('Curvature','number')],([g,t])=>{let c=NurbsCurve.from(g);return [c.at(t),V.unit(c.derivative(t)),c.curvature(t)];});
define('loft','Loft','Surface',[port('Curves','any','curves',undefined,'list')],[output('Surface','surface')],([curves])=>[loftSurface(curves).toJSON()],{preview:true});
define('extrude','Extrude','Surface',[port('Curve','curve','curve'),port('Vector','vector','vector',[0,0,10])],[output('Geometry','geometry')],([g,v])=>[{kind:'extrusion',profile:g,vector:v,cap:true}],{preview:true});
define('revolve','Revolve','Surface',[port('Profile','curve','curve'),N('Angle °','angle',360)],[output('Surface','surface')],([g,a])=>[revolveSurface(g,a*Math.PI/180).toJSON()],{preview:true});
define('sweep','Sweep one rail','Surface',[port('Profile','curve','profile'),port('Rail','curve','rail')],[output('Surface','surface')],([p,r])=>[sweepSurface(p,r).toJSON()],{preview:true});
define('pipe','Pipe','Surface',[port('Rail','curve','rail'),N('Radius','radius',.3)],[output('Geometry','geometry')],([rail,radius])=>{positive(radius);return [{kind:'pipe',rail,radius}];},{preview:true});
define('evaluatesurface','Evaluate surface','Surface',[port('Surface','surface','surface'),N('U','u',.5),N('V','v',.5)],[output('Point','point'),output('Normal','vector')],([g,u,v])=>{let e=NurbsSurface.from(g).evaluate(u,v);return [e.point,e.normal];});
define('isocurve','Surface isocurve','Surface',[port('Surface','surface','surface'),N('U','u',.5)],[output('Curve','curve')],([g,u])=>{let s=NurbsSurface.from(g),p=Array.from({length:25},(_,i)=>s.at(u,i/24));return [interpolateCurve(p,3).toJSON()];},{preview:true});
define('canopy','Canopy surface','Surface',[N('Span','span',28),N('Rise','rise',11),N('Twist','twist',4),N('Depth','depth',13)],[output('Surface','surface')],([a,b,c,d])=>[canopySurface(a,b,c,d)],{preview:true});
define('ribs','Surface ribs','Surface',[port('Surface','surface','surface'),N('Count','count',32),N('Radius','radius',.075)],[output('Mesh','mesh')],([s,n,r])=>[canopyRibs(s,n,r)],{preview:true});
define('box','Box','Solid',[N('Width','width',6),N('Depth','depth',6),N('Height','height',6)],[output('Geometry','geometry')],([width,depth,height])=>{positive(width,depth,height);return [{kind:'box',width,depth,height}];},{preview:true});
define('sphere','Sphere','Solid',[port('Center','point','center',[0,0,0]),N('Radius','radius',5)],[output('Geometry','geometry')],([p,radius])=>{positive(radius);return [transformGeometry({kind:'sphere',radius},M.translation(p))];},{preview:true});
define('cylinder','Cylinder','Solid',[N('Radius','radius',3),N('Height','height',8)],[output('Geometry','geometry')],([radius,height])=>{positive(radius,height);return [{kind:'cylinder',radius,height}];},{preview:true});
define('torus','Torus','Solid',[N('Major radius','major',6),N('Minor radius','minor',1.5)],[output('Geometry','geometry')],([major,minor])=>{positive(major,minor);if(major<=minor)throw Error('Major radius must exceed minor radius');return [{kind:'torus',major,minor}];},{preview:true});
for(let [id,name,mode] of [['union','Mesh union','union'],['difference','Mesh difference','difference'],['intersection','Mesh intersection','intersection']])define(id,name,'Solid',[G('A','a'),G('B','b')],[output('Mesh','mesh')],([a,b])=>[booleanMesh(geometryMesh(a,.5),geometryMesh(b,.5),mode)],{preview:true});
define('move','Move','Transform',[G('Geometry','geometry'),port('Motion','vector','vector',[0,0,5])],[output('Geometry','geometry')],([g,v])=>[transformGeometry(g,M.translation(v))],{preview:true});
define('rotate','Rotate Z','Transform',[G('Geometry','geometry'),N('Angle °','angle',45)],[output('Geometry','geometry')],([g,a])=>[transformGeometry(g,M.rotation([0,0,1],a*Math.PI/180))],{preview:true});
define('scale','Scale','Transform',[G('Geometry','geometry'),N('Factor','factor',2)],[output('Geometry','geometry')],([g,s])=>{if(s===0)throw Error('Scale must be nonzero');return [transformGeometry(g,M.scaling(s))];},{preview:true});
define('mesh','Mesh geometry','Mesh',[G('Geometry','geometry'),N('Quality','quality',1)],[output('Mesh','mesh')],([g,q])=>{let m=geometryMesh(g,clamp(q,.25,3));if(!m)throw Error('Input has no surface');return [m];},{preview:true});
define('subdivide','Loop subdivision','Mesh',[port('Mesh','mesh','mesh'),N('Iterations','iterations',1)],[output('Mesh','mesh')],([m,n])=>[subdivideMesh(m,clamp(Math.round(n),0,3))],{preview:true});
define('area','Area / volume','Analysis',[G('Geometry','geometry')],[output('Area','number'),output('Volume','number')],([g])=>{let m=geometryMesh(g);if(!m)throw Error('Expected a surface or mesh');let a=analyzeMesh(m);return [a.area,a.closed?a.volume:0];});
define('section','Section','Analysis',[G('Geometry','geometry'),N('Height','height',3)],[output('Geometry','geometry')],([g,h])=>[{kind:'lines',segments:sectionMesh(geometryMesh(g),[0,0,h])}],{preview:true});
define('reference','Geometry reference','Params',[],[output('Geometry','geometry')],(_,p,ctx)=>{let o=ctx.document?.get(p.objectId);if(!o)throw Error('Choose a document object in the component inspector');return [transformGeometry(o.geometry,o.matrix)];},{defaults:{objectId:''}});
export function createDemoGraph(graph){
  graph.enabled=false;
  let span=graph.add('number',40,55,{value:28,min:12,max:42,step:.1});span.label='Span';
  let rise=graph.add('number',40,145,{value:11,min:3,max:20,step:.1});rise.label='Rise';
  let twist=graph.add('number',40,235,{value:5,min:-12,max:12,step:.1});twist.label='Twist';
  let canopy=graph.add('canopy',320,96),count=graph.add('number',320,295,{value:36,min:8,max:80,step:1});count.label='Rib count';
  let ribs=graph.add('ribs',615,120,{radius:.065}),area=graph.add('area',875,102),panel=graph.add('panel',1100,100);
  graph.connect(span.id,0,canopy.id,0);graph.connect(rise.id,0,canopy.id,1);graph.connect(twist.id,0,canopy.id,2);graph.connect(canopy.id,0,ribs.id,0);graph.connect(count.id,0,ribs.id,1);graph.connect(canopy.id,0,area.id,0);graph.connect(area.id,0,panel.id,0);graph.enabled=true;return {span,rise,twist,canopy,count,ribs};
}
