import {V,M,bounds,EPS} from './math.js';
export function mesh(positions=[],indices=[],normals=null,edges=null){let m={kind:'mesh',positions,indices,normals,edges};if(!normals)recomputeNormals(m);return m;}
export function recomputeNormals(m){m.normals=m.positions.map(()=>[0,0,0]);for(let i=0;i<m.indices.length;i+=3){let [a,b,c]=m.indices.slice(i,i+3),n=V.cross(V.sub(m.positions[b],m.positions[a]),V.sub(m.positions[c],m.positions[a]));for(let j of [a,b,c])m.normals[j]=V.add(m.normals[j],n);}m.normals=m.normals.map(V.unit);return m;}
export function meshEdges(m,featureOnly=false,angle=25){
  let map=new Map(),out=[];for(let i=0;i<m.indices.length;i+=3){let t=m.indices.slice(i,i+3),n=V.unit(V.cross(V.sub(m.positions[t[1]],m.positions[t[0]]),V.sub(m.positions[t[2]],m.positions[t[0]])));for(let j=0;j<3;j++){let a=t[j],b=t[(j+1)%3],key=a<b?a+':'+b:b+':'+a;if(!map.has(key))map.set(key,{a,b,n,count:1,sharp:false});else{let e=map.get(key);e.count++;e.sharp ||=V.dot(n,e.n)<Math.cos(angle*Math.PI/180);}}}for(let e of map.values())if(!featureOnly||e.count===1||e.sharp)out.push([m.positions[e.a],m.positions[e.b]]);return out;
}
export function transformMesh(m,mat){let normalMatrix=M.transpose(M.inverse(mat)),det=V.dot(M.vector(mat,[1,0,0]),V.cross(M.vector(mat,[0,1,0]),M.vector(mat,[0,0,1]))),indices=[...m.indices];if(det<0)for(let i=0;i<indices.length;i+=3)[indices[i+1],indices[i+2]]=[indices[i+2],indices[i+1]];return mesh(m.positions.map(p=>M.point(mat,p)),indices,m.normals.map(n=>V.unit(M.vector(normalMatrix,n))),m.edges?.map(e=>e.map(p=>M.point(mat,p))));}
export function mergeMeshes(meshes){let P=[],I=[],N=[],E=[];for(let m of meshes){let offset=P.length;P.push(...m.positions);I.push(...m.indices.map(i=>i+offset));N.push(...m.normals);if(m.edges)E.push(...m.edges);}return mesh(P,I,N,E.length?E:null);}
export function weldMesh(m,tolerance=1e-7){
  if(!(tolerance>0))throw Error('Weld tolerance must be positive');let bins=new Map(),P=[],remap=[];for(let p of m.positions){let c=p.map(v=>Math.floor(v/tolerance)),found=-1;outer:for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++){let key=[c[0]+x,c[1]+y,c[2]+z].join(','),bucket=bins.get(key);if(bucket)for(let j of bucket)if(V.distance(P[j],p)<=tolerance){found=j;break outer;}}if(found<0){found=P.length;P.push([...p]);let key=c.join(',');if(!bins.has(key))bins.set(key,[]);bins.get(key).push(found);}remap.push(found);}let I=[];for(let i=0;i<m.indices.length;i+=3){let t=m.indices.slice(i,i+3).map(j=>remap[j]);if(new Set(t).size===3&&V.length(V.cross(V.sub(P[t[1]],P[t[0]]),V.sub(P[t[2]],P[t[0]])))>tolerance*tolerance)I.push(...t);}return mesh(P,I);
}
export function analyzeMesh(m,tolerance=1e-6){
  let w=weldMesh(m,tolerance),area=0,volume=0,centroid=[0,0,0],edgeCounts=new Map(),orientedEdges=new Map(),degenerate=0;
  for(let i=0;i<w.indices.length;i+=3){let t=w.indices.slice(i,i+3),[a,b,c]=t.map(j=>w.positions[j]),cross=V.cross(V.sub(b,a),V.sub(c,a)),A=V.length(cross)/2;if(A<tolerance*tolerance)degenerate++;area+=A;let v=V.dot(a,V.cross(b,c))/6;volume+=v;centroid=V.add(centroid,V.mul(V.add(V.add(a,b),c),v/4));for(let j=0;j<3;j++){let x=t[j],y=t[(j+1)%3],key=x<y?x+':'+y:y+':'+x;edgeCounts.set(key,(edgeCounts.get(key)||0)+1);orientedEdges.set(key,(orientedEdges.get(key)||0)+(x<y?1:-1));}}
  let naked=[...edgeCounts.values()].filter(n=>n===1).length,nonManifold=[...edgeCounts.values()].filter(n=>n>2).length,inconsistent=[...orientedEdges].filter(([k,n])=>edgeCounts.get(k)===2&&n!==0).length;
  return {vertices:w.positions.length,faces:w.indices.length/3,edges:edgeCounts.size,area,volume:Math.abs(volume),signedVolume:volume,centroid:Math.abs(volume)>1e-12?V.mul(centroid,1/volume):[0,0,0],nakedEdges:naked,nonManifoldEdges:nonManifold,inconsistentEdges:inconsistent,degenerateFaces:degenerate,closed:naked===0&&nonManifold===0&&inconsistent===0,bounds:bounds(w.positions)};
}
/** Ear clipping for a simple, planar polygon; holes and self intersections are rejected. */
export function triangulatePolygon(points){
  if(points.length<3)throw Error('A cap needs at least 3 vertices');let n=[0,0,0];for(let i=0;i<points.length;i++){let a=points[i],b=points[(i+1)%points.length];n=V.add(n,[(a[1]-b[1])*(a[2]+b[2]),(a[2]-b[2])*(a[0]+b[0]),(a[0]-b[0])*(a[1]+b[1])]);}if(V.length(n)<1e-10)throw Error('Degenerate or self-intersecting cap');n=V.unit(n);let span=bounds(points).size,scale=Math.max(...span,1);if(points.some(p=>Math.abs(V.dot(V.sub(p,points[0]),n))>scale*1e-6))throw Error('Capping requires a planar closed profile');let axis=n.map(Math.abs).indexOf(Math.max(...n.map(Math.abs))),coords=points.map(p=>p.filter((_,i)=>i!==axis)),cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]),area=coords.reduce((s,a,i)=>{let b=coords[(i+1)%coords.length];return s+a[0]*b[1]-a[1]*b[0];},0),sign=area>0?1:-1,ring=coords.map((_,i)=>i),out=[];
  const eps=scale*scale*1e-12,onSegment=(a,b,p)=>Math.abs(cross(a,b,p))<=eps&&p[0]>=Math.min(a[0],b[0])-1e-10&&p[0]<=Math.max(a[0],b[0])+1e-10&&p[1]>=Math.min(a[1],b[1])-1e-10&&p[1]<=Math.max(a[1],b[1])+1e-10;
  for(let i=0;i<coords.length;i++)for(let j=i+1;j<coords.length;j++){let i1=(i+1)%coords.length,j1=(j+1)%coords.length;if(i===j||i1===j||j1===i)continue;let a=coords[i],b=coords[i1],c=coords[j],d=coords[j1],abC=cross(a,b,c),abD=cross(a,b,d),cdA=cross(c,d,a),cdB=cross(c,d,b);if((abC*abD<0&&cdA*cdB<0)||onSegment(a,b,c)||onSegment(a,b,d)||onSegment(c,d,a)||onSegment(c,d,b))throw Error('Profile is self-intersecting or has touching nonadjacent edges');}
  let tries=0;while(ring.length>3){let clipped=false;for(let i=0;i<ring.length;i++){let a=ring[(i+ring.length-1)%ring.length],b=ring[i],c=ring[(i+1)%ring.length];if(cross(coords[a],coords[b],coords[c])*sign<1e-12)continue;let inside=ring.some(j=>j!==a&&j!==b&&j!==c&&cross(coords[a],coords[b],coords[j])*sign>=-1e-12&&cross(coords[b],coords[c],coords[j])*sign>=-1e-12&&cross(coords[c],coords[a],coords[j])*sign>=-1e-12);if(!inside){out.push(a,b,c);ring.splice(i,1);clipped=true;break;}}if(!clipped||++tries>points.length**2)throw Error('Profile is self-intersecting or contains coincident vertices');}out.push(...ring);return out;
}
export function boxMesh(w=10,d=10,h=10){
  if(Math.min(w,d,h)<=0)throw Error('Box dimensions must be positive');let x=w/2,y=d/2,P=[],I=[],N=[],E=[];
  let corners=[[-x,-y,0],[x,-y,0],[x,y,0],[-x,y,0],[-x,-y,h],[x,-y,h],[x,y,h],[-x,y,h]],faces=[[0,3,2,1],[4,5,6,7],[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7]];
  for(let f of faces){let base=P.length,pts=f.map(i=>corners[i]),n=V.unit(V.cross(V.sub(pts[1],pts[0]),V.sub(pts[2],pts[0])));P.push(...pts);N.push(n,n,n,n);I.push(base,base+1,base+2,base,base+2,base+3);}for(let [a,b] of [[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]])E.push([corners[a],corners[b]]);return mesh(P,I,N,E);
}
export function sphereMesh(r=5,nu=48,nv=24){if(!(r>0))throw Error('Radius must be positive');let P=[],N=[],I=[],E=[];for(let j=0;j<=nv;j++)for(let i=0;i<=nu;i++){let t=j/nv*Math.PI,p=i/nu*2*Math.PI,n=[Math.sin(t)*Math.cos(p),Math.sin(t)*Math.sin(p),Math.cos(t)];N.push(n);P.push(V.mul(n,r));}for(let j=0;j<nv;j++)for(let i=0;i<nu;i++){let a=j*(nu+1)+i,b=a+1,c=a+nu+1,d=c+1;if(j>0)I.push(a,c,b);if(j<nv-1)I.push(b,c,d);}for(let j=1;j<nv;j++)if(j%(nv/4|0)===0)for(let i=0;i<nu;i++){let a=j*(nu+1)+i;E.push([P[a],P[a+1]]);}for(let i=0;i<nu;i+=nu/4|0)for(let j=0;j<nv;j++){let a=j*(nu+1)+i;E.push([P[a],P[a+nu+1]]);}return mesh(P,I,N,E);}
export function cylinderMesh(r=5,h=10,segments=48,topRadius=r){
  if(!(r>0&&h>0&&topRadius>=0))throw Error('Invalid cylinder dimensions');let P=[],I=[],N=[],E=[];for(let j=0;j<2;j++)for(let i=0;i<=segments;i++){let a=i/segments*Math.PI*2,rad=j?topRadius:r;P.push([rad*Math.cos(a),rad*Math.sin(a),j*h]);N.push(V.unit([Math.cos(a),Math.sin(a),(r-topRadius)/h]));}for(let i=0;i<segments;i++){let a=i,b=i+1,c=i+segments+1,d=c+1;I.push(a,b,c);if(topRadius>0)I.push(b,d,c);E.push([P[a],P[b]]);if(topRadius>0)E.push([P[c],P[d]]);if(i%(segments/4|0)===0)E.push([P[a],P[c]]);}
  for(let j=0;j<2;j++){if(j&&topRadius===0)continue;let center=P.length;P.push([0,0,j*h]);N.push([0,0,j?1:-1]);for(let i=0;i<=segments;i++){let a=i/segments*2*Math.PI,rad=j?topRadius:r;P.push([rad*Math.cos(a),rad*Math.sin(a),j*h]);N.push([0,0,j?1:-1]);}for(let i=0;i<segments;i++)if(j)I.push(center,center+i+1,center+i+2);else I.push(center,center+i+2,center+i+1);}return mesh(P,I,N,E);
}
export function torusMesh(major=6,minor=1.5,nu=64,nv=20){if(!(major>minor&&minor>0))throw Error('Major radius must exceed the positive tube radius');let P=[],N=[],I=[],E=[];for(let j=0;j<=nv;j++)for(let i=0;i<=nu;i++){let u=i/nu*2*Math.PI,v=j/nv*2*Math.PI;P.push([(major+minor*Math.cos(v))*Math.cos(u),(major+minor*Math.cos(v))*Math.sin(u),minor*Math.sin(v)]);N.push([Math.cos(v)*Math.cos(u),Math.cos(v)*Math.sin(u),Math.sin(v)]);}for(let j=0;j<nv;j++)for(let i=0;i<nu;i++){let a=j*(nu+1)+i,b=a+1,c=a+nu+1,d=c+1;I.push(a,b,c,b,d,c);if(j%(nv/4|0)===0)E.push([P[a],P[b]]);if(i%(nu/8|0)===0)E.push([P[a],P[c]]);}return mesh(P,I,N,E);}
export function surfaceMesh(surface,nu=48,nv=24){let P=[],N=[],I=[],E=[];nu=Math.max(2,nu|0);nv=Math.max(2,nv|0);for(let j=0;j<=nv;j++)for(let i=0;i<=nu;i++){let e=surface.evaluate(i/nu,j/nv);P.push(e.point);N.push(e.normal);}for(let j=0;j<nv;j++)for(let i=0;i<nu;i++){let a=j*(nu+1)+i,b=a+1,c=a+nu+1,d=c+1;I.push(a,b,c,b,d,c);}for(let j=0;j<=nv;j++)if(j===nv||j%Math.max(1,Math.floor(nv/8))===0)for(let i=0;i<nu;i++){let a=j*(nu+1)+i;E.push([P[a],P[a+1]]);}for(let i=0;i<=nu;i++)if(i===nu||i%Math.max(1,Math.floor(nu/12))===0)for(let j=0;j<nv;j++){let a=j*(nu+1)+i;E.push([P[a],P[a+nu+1]]);}return mesh(P,I,N,E);}
export function extrudeMesh(points,vector,cap=true){
  if(points.length<2||!vector.every(Number.isFinite)||V.length(vector)<1e-12)throw Error('Extrusion needs a profile and nonzero finite vector');
  let P=points.map(p=>[...p]),closed=V.equal(P[0],P.at(-1),1e-6);if(closed)P.pop();let capI=null;
  if(closed&&cap){capI=triangulatePolygon(P);let [a,b,c]=capI.slice(0,3).map(i=>P[i]),dot=V.dot(V.cross(V.sub(b,a),V.sub(c,a)),vector);if(Math.abs(dot)<1e-12)throw Error('Extrusion vector lies in the profile plane');if(dot<0){P.reverse();capI=triangulatePolygon(P);}}
  let n=P.length,I=[],E=[];P.push(...P.map(p=>V.add(p,vector)));for(let i=0;i<(closed?n:n-1);i++){let j=(i+1)%n;I.push(i,j,i+n,j,j+n,i+n);E.push([P[i],P[j]],[P[i+n],P[j+n]]);}
  if(capI)for(let k=0;k<capI.length;k+=3){let [x,y,z]=capI.slice(k,k+3);I.push(x,z,y,x+n,y+n,z+n);}return mesh(P,I,null,E);
}
export function pipeMesh(points,radius=.2,segments=10,cap=true){
  if(points.length<2||radius<=0)throw Error('A pipe needs a rail and positive radius');let P=[],I=[],E=[],previous=null;for(let j=0;j<points.length;j++){let tangent=V.unit(V.sub(points[Math.min(j+1,points.length-1)],points[Math.max(0,j-1)]));let normal=previous?V.unit(V.sub(previous,V.mul(tangent,V.dot(previous,tangent)))):V.unit(V.cross(tangent,Math.abs(tangent[2])>.9?[1,0,0]:[0,0,1]));if(V.length(normal)<.1)normal=V.unit(V.cross(tangent,[0,1,0]));previous=normal;let binormal=V.cross(tangent,normal);for(let i=0;i<segments;i++){let a=i/segments*2*Math.PI;P.push(V.add(points[j],V.mul(V.add(V.mul(normal,Math.cos(a)),V.mul(binormal,Math.sin(a))),radius)));}}
  for(let j=0;j<points.length-1;j++)for(let i=0;i<segments;i++){let a=j*segments+i,b=j*segments+(i+1)%segments,c=a+segments,d=b+segments;I.push(a,b,c,b,d,c);if(i===0)E.push([P[a],P[c]]);}if(cap){let a=P.length;P.push(points[0],points.at(-1));for(let i=0;i<segments;i++){let k=(i+1)%segments;I.push(a,k,i,a+1,(points.length-1)*segments+i,(points.length-1)*segments+k);}}return mesh(P,I,null,E);
}
/** Loop subdivision with boundary rules on a welded triangle manifold. */
export function subdivideMesh(input,iterations=1){
  if(iterations<0||iterations>3)throw Error('Subdivision supports 0–3 iterations');let m=weldMesh(input);
  for(let step=0;step<iterations;step++){if(m.indices.length>1500000)throw Error('Subdivision triangle budget exceeded');let neighbors=m.positions.map(()=>new Set()),edges=new Map();for(let i=0;i<m.indices.length;i+=3){let t=m.indices.slice(i,i+3);for(let j=0;j<3;j++){let a=t[j],b=t[(j+1)%3],op=t[(j+2)%3],key=a<b?a+':'+b:b+':'+a;neighbors[a].add(b);neighbors[b].add(a);if(!edges.has(key))edges.set(key,{a,b,op:[]});edges.get(key).op.push(op);}}if([...edges.values()].some(e=>e.op.length>2))throw Error('Subdivision requires a manifold mesh');let boundary=m.positions.map(()=>[]);for(let e of edges.values())if(e.op.length===1){boundary[e.a].push(e.b);boundary[e.b].push(e.a);}let P=m.positions.map((p,i)=>{if(boundary[i].length===2)return V.add(V.mul(p,.75),V.mul(V.add(...boundary[i].map(j=>m.positions[j])),.125));let ns=[...neighbors[i]],n=ns.length;if(!n)return p;let beta=n===3?3/16:3/(8*n);return V.add(V.mul(p,1-n*beta),ns.reduce((s,j)=>V.add(s,V.mul(m.positions[j],beta)),[0,0,0]));});
    for(let e of edges.values()){e.index=P.length;let a=m.positions[e.a],b=m.positions[e.b];P.push(e.op.length===1?V.mix(a,b,.5):V.add(V.mul(V.add(a,b),3/8),V.mul(V.add(m.positions[e.op[0]],m.positions[e.op[1]]),1/8)));}let I=[],edge=(a,b)=>edges.get(a<b?a+':'+b:b+':'+a).index;for(let i=0;i<m.indices.length;i+=3){let [a,b,c]=m.indices.slice(i,i+3),ab=edge(a,b),bc=edge(b,c),ca=edge(c,a);I.push(a,ab,ca,b,bc,ab,c,ca,bc,ab,bc,ca);}m=mesh(P,I);
  }return m;
}
export function sectionMesh(m,origin=[0,0,0],normal=[0,0,1]){normal=V.unit(normal);let segments=[];for(let i=0;i<m.indices.length;i+=3){let tri=m.indices.slice(i,i+3).map(j=>m.positions[j]),hits=[];for(let j=0;j<3;j++){let a=tri[j],b=tri[(j+1)%3],da=V.dot(V.sub(a,origin),normal),db=V.dot(V.sub(b,origin),normal);if((da<0&&db>=0)||(da>=0&&db<0))hits.push(V.mix(a,b,da/(da-db)));}if(hits.length===2&&V.distance(...hits)>1e-8)segments.push(hits);}return segments;}
