import {V,M,clamp,uid} from './core/math.js';
import {Document,makeObject} from './core/document.js';
import {NurbsCurve,NurbsSurface,circleCurve,interpolateCurve,polyline,rectangle,transformGeometry} from './core/geometry.js';
import {analyzeMesh} from './core/mesh.js';
import {MeshBVH} from './core/spatial.js';
import {Graph} from './core/graph.js';
import {COMPONENTS,createDemoGraph} from './core/components.js';
import {download,importOBJ,importSTL,importDXF} from './core/io.js';
import {Renderer} from './render/renderer.js';
import {Camera} from './render/camera.js';
import {$,$$,escape,icon,toast,menu,closePopups,searchPopup,formDialog} from './ui/ui.js';
import {GraphView} from './ui/graph-view.js';
import {Commands,MENUS,TOOLBARS} from './ui/commands.js';
const STORAGE_KEY='veldra.workspace.v1';
const MODES=['Shaded','Wireframe','Rendered','Zebra','Normals'];
class VeldraApp{
  constructor(){
    this.doc=new Document();this.graph=new Graph(COMPONENTS);this.commands=new Commands(this);this.history=[];this.flags={grid:true,snap:false,ortho:false,osnap:true,gumball:true,points:false};this.cameras={Perspective:new Camera(),Top:new Camera('Top'),Front:new Camera('Front'),Right:new Camera('Right')};this.activeView='Perspective';this.four=false;this.previews=[];this.previewMap=new Map();this.selectedNode=null;this.panel='properties';this.tool=null;this.controlHandles=[];this.gumballHandles=[];this.renderRequested=false;this.solveRequested=false;this.ready=false;this.saving=false;this.editing=null;this.pointer=null;this.autosaveTimer=null;this.snapPoint=null;this.showCaption=true;
  }
  async start(){
    this.setupDemoData();let stored;try{stored=!location.search.includes('fresh')?JSON.parse(localStorage.getItem(STORAGE_KEY)??'null'):null;if(stored){this.doc.restore(stored);if(stored.extra?.graph)this.graph.restore(stored.extra.graph);this.showCaption=false;}}catch(e){console.warn('Autosave recovery',e);this.setupDemoData();}
    this.buildUI();this.graphView=new GraphView(this.graph,{onSelect:id=>{this.selectedNode=id;this.updateInspector();this.rebuildScene();},onChange:reason=>{if(reason!=='layout')this.requestSolve();this.autosave();}});
    this.graph.evaluate({document:this.doc,version:this.doc.version});this.graphView.refresh();
    try{this.renderer=await new Renderer($('#render-canvas')).init();this.renderer.onError=message=>toast(message,true);if(this.renderer.fallbackReason)this.log(this.renderer.backend+' ('+this.renderer.fallbackReason+').');}catch(e){$('#loading').innerHTML=`<strong>Graphics initialization failed</strong><span>${escape(e.message)}</span><span>Use a browser with WebGPU or WebGL2 enabled.</span>`;throw e;}
    this.installViewEvents();this.installEvents();this.doc.onChange(reason=>{if(reason==='restore'){this.previewMap.clear();}this.updateUI();this.rebuildScene();if(!['selection','drag'].includes(reason))this.requestSolve();this.autosave();});
    this.doc.restoreRelated=data=>this.graph.restore(data);this.ready=true;this.autosave();$('#loading').remove();this.updatePreviews();this.updateUI();this.graphView.fit();this.invalidate();
    $('#renderer-status').innerHTML=`<i class="gpu-dot"></i> ${this.renderer.backend}`;$('#renderer-status').title=this.renderer.backend==='WebGPU'?JSON.stringify(this.renderer.adapterInfo??{}):this.renderer.fallbackReason;
    this.log(`Ready. ${this.renderer.backend} · ${Object.keys(COMPONENTS).length} Weave components · units ${this.doc.units}.`);
    this.resizeObserver=new ResizeObserver(entries=>{if(entries.some(e=>e.target.id==='graph-canvas'))this.graphView.fit();this.updateViewLabels();this.invalidate();});this.resizeObserver.observe($('#viewport-area'));this.resizeObserver.observe($('#graph-canvas'));
    window.veldra=this;
  }
  setupDemoData(){
    this.doc=new Document();this.commands=new Commands(this);this.doc.name='Canopy study';this.doc.layers=[{id:'model',name:'Default',color:'#80a497',visible:true,locked:false},{id:'structure',name:'Structure',color:'#526968',visible:true,locked:false},{id:'site',name:'Site & context',color:'#c4c5c0',visible:true,locked:false},{id:'reference',name:'Reference',color:'#90a3b0',visible:true,locked:false}];
    this.doc.add({kind:'box',width:34,depth:18,height:.3},'Exhibition plinth',{layer:'site',color:'#c9cfcc',matrix:M.translation([0,0,-.32]),material:{metallic:0,roughness:.92}});
    this.doc.add({kind:'box',width:35.6,depth:19.6,height:.16},'Base / lower course',{layer:'site',color:'#b6beba',matrix:M.translation([0,0,-.49]),material:{metallic:0,roughness:1}});
    for(let x of [-14,14])this.doc.add({kind:'box',width:.6,depth:13.6,height:.46},x<0?'West bearing':'East bearing',{layer:'structure',color:'#718e82',matrix:M.translation([x,0,-.01]),material:{metallic:.35,roughness:.33}});
    this.graph=new Graph(COMPONENTS);this.demoNodes=createDemoGraph(this.graph);this.doc.extra.graph=this.graph.serialize();
  }
  buildUI(){
    $('#menubar').innerHTML=Object.keys(MENUS).map(name=>`<button data-menu="${name}">${name}</button>`).join('');$('#menubar').onclick=e=>{let b=e.target.closest('[data-menu]');if(!b)return;let items=MENUS[b.dataset.menu].map(id=>id===null?null:{...this.commands.items.get(id),action:()=>this.run(id)}),r=b.getBoundingClientRect();menu(items,r.left,r.bottom+3);};
    $('#ribbon-tabs').innerHTML=Object.keys(TOOLBARS).map((t,i)=>`<button data-tab="${t}" class="${i?'':'active'}">${t}</button>`).join('');$('#ribbon-tabs').onclick=e=>{let b=e.target.closest('[data-tab]');if(b)this.showToolbar(b.dataset.tab);};this.showToolbar('Standard');
    $('#toolrail').innerHTML=['select','points',null,'point','line','curve','circle','rectangle',null,'box','surface','extrude','loft',null,'move','rotate','scale',null,'analyze'].map(id=>{if(!id)return '<span class="separator"></span>';let c=this.commands.items.get(id);return `<button data-command="${id}" title="${c.label}" aria-label="${c.label}">${icon(c.icon)}</button>`;}).join('');
    $('#theme-button').innerHTML=icon('sun');$('#fourview-button').innerHTML=icon('fourview');$('#fit-view-button').innerHTML=icon('fit');$('#theme-button').onclick=()=>{document.body.classList.toggle('dark');try{localStorage.setItem('veldra.theme',document.body.classList.contains('dark')?'dark':'light');}catch{}};try{if(localStorage.getItem('veldra.theme')==='dark')document.body.classList.add('dark');}catch{}
    $('#display-button').onclick=()=>{let r=$('#display-button').getBoundingClientRect();menu(MODES.map((label,mode)=>({label,icon:mode===3?'analyze':'render',action:()=>this.setDisplay(mode)})),r.left,r.bottom+4);};$('#graph-bake').onclick=()=>this.bake();
  }
  showToolbar(tab){for(let b of $$('#ribbon-tabs button'))b.classList.toggle('active',b.dataset.tab===tab);$('#ribbon-tools').innerHTML=TOOLBARS[tab].map(id=>{if(!id)return '<span class="tool-divider"></span>';let c=this.commands.items.get(id);return `<button data-command="${id}" title="${c.label}${c.shortcut?' · '+c.shortcut:''}">${icon(c.icon)}<span>${escape(({zoomextents:'Fit',fourview:'4 views',select:'Select',new:'New',open:'Open',save:'Save',curve:'Curve',move:'Move',rotate:'Rotate',scale:'Scale',extrude:'Extrude',loft:'Loft',undo:'Undo',redo:'Redo'})[id]??c.label)}</span></button>`;}).join('')+'<span class="shortcut-hint">PRECISION MODELING</span>';}
  async run(command){try{await this.commands.execute(command);}catch(e){this.log('Error: '+e.message);toast(e.message,true);console.error(e);}}
  log(text){this.history.push({time:new Date().toLocaleTimeString(),text});if(this.history.length>250)this.history.shift();$('#last-command').textContent=text;$('#history-panel').innerHTML=this.history.map(h=>`<div><span class="muted">${h.time}</span> ${escape(h.text)}</div>`).join('');$('#history-panel').scrollTop=1e9;}
  palette(){searchPopup({title:'Search modeling commands…',items:[...this.commands.items.values()],onChoose:c=>this.run(c.id)});}
  installEvents(){
    document.addEventListener('click',e=>{let b=e.target.closest('[data-command]');if(b){e.preventDefault();this.run(b.dataset.command);}});
    document.addEventListener('pointerdown',e=>{if(!e.target.closest('.popup')&&!e.target.closest('#menubar'))closePopups();});
    $('#command-input').addEventListener('keydown',e=>{if(e.key==='Enter'){let value=e.target.value;e.target.value='';if(this.tool&&/^[\d\s,.-]+$/.test(value)){let point=value.trim().split(/[,\s]+/).map(Number);if(point.length>=2){if(point.length===2)point.push(0);this.addToolPoint(point);return;}}this.run(value);e.target.blur();$('#viewport-area').focus();}if(e.key==='Escape'){e.target.value='';e.target.blur();this.cancelTool();}});
    $('#history-toggle').onclick=()=>{$('#history-panel').hidden=!$('#history-panel').hidden;};
    $('#inspector-tabs').onclick=e=>{let b=e.target.closest('[data-panel]');if(b){this.panel=b.dataset.panel;this.updateInspector(true);}};
    $('#file-input').onchange=async e=>{let file=e.target.files[0];e.target.value='';if(file)try{await this.importFile(file);}catch(error){toast(error.message,true);this.log('Import error: '+error.message);}};
    let resize=null;$('#graph-resizer').onpointerdown=e=>{resize={y:e.clientY,height:$('#weave-panel').clientHeight};$('#graph-resizer').setPointerCapture(e.pointerId);};$('#graph-resizer').onpointermove=e=>{if(resize){document.documentElement.style.setProperty('--graph-height',clamp(resize.height+resize.y-e.clientY,145,innerHeight*.7)+'px');this.invalidate();}};$('#graph-resizer').onpointerup=()=>resize=null;
    document.addEventListener('keydown',e=>{let editing=e.target.matches('input,textarea,select')||$('#form-dialog').open;if(editing)return;let meta=e.ctrlKey||e.metaKey,key=e.key.toLowerCase();if(meta){let cmd=({s:'save',o:'open',n:'new',z:e.shiftKey?'redo':'undo',y:'redo',a:'selectall',c:'copy',v:'paste',d:'duplicate'})[key];if(cmd){e.preventDefault();this.run(cmd);return;}}if(e.key==='Escape'){closePopups();if(this.tool)this.cancelTool();else{this.doc.select([]);this.graphView.select(null);this.selectedControl=null;this.invalidate();}return;}if(e.key==='Enter'&&this.tool){e.preventDefault();this.finishTool();return;}if(e.key==='Delete'||e.key==='Backspace'){if(this.doc.selection.size){e.preventDefault();this.run('delete');}return;}if(e.key==='/'){e.preventDefault();this.palette();return;}let cmd=({w:'weave',f:'zoomselected',m:'move',home:'zoomextents',f4:'fourview',f3:'osnap',f8:'ortho','?':'help'})[key];if(cmd){e.preventDefault();this.run(cmd);return;}if(e.key===' '){e.preventDefault();if(e.target.closest('#graph-canvas'))this.graphView.library();else this.palette();}});
    $('#viewport-area').addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';});$('#viewport-area').addEventListener('drop',async e=>{e.preventDefault();let file=e.dataTransfer.files[0];if(file)try{await this.importFile(file);}catch(error){toast(error.message,true);}});
  }
  getViewports(){let area=$('#viewport-area'),w=area.clientWidth,h=area.clientHeight;if(this.four){let hw=w/2,hh=h/2;return [{name:'Top',camera:this.cameras.Top,x:0,y:0,width:hw,height:hh},{name:'Perspective',camera:this.cameras.Perspective,x:hw,y:0,width:hw,height:hh},{name:'Front',camera:this.cameras.Front,x:0,y:hh,width:hw,height:hh},{name:'Right',camera:this.cameras.Right,x:hw,y:hh,width:hw,height:hh}];}return [{name:this.activeView,camera:this.cameras[this.activeView],x:0,y:0,width:w,height:h}];}
  viewAt(x,y){return this.getViewports().find(v=>x>=v.x&&x<v.x+v.width&&y>=v.y&&y<v.y+v.height)??this.getViewports()[0];}
  updateViewLabels(){if(!this.renderer)return;$('#viewport-labels').innerHTML=this.getViewports().map(v=>`<div class="viewport-label ${v.name===this.activeView?'active':''}" style="left:${v.x+12}px;top:${v.y+12}px" data-view="${v.name}">${v.name} <span style="font-size:8px;opacity:.6">⌄</span></div>`).join('')+(this.four?'<div class="viewport-divider-v"></div><div class="viewport-divider-h"></div>':'');$('.viewport-caption').classList.toggle('hidden',!this.showCaption||this.four||this.activeView!=='Perspective');$('#viewport-labels').ondblclick=e=>{let b=e.target.closest('[data-view]');if(b){this.activeView=b.dataset.view;this.toggleFour();}};$('#viewport-labels').onclick=e=>{let b=e.target.closest('[data-view]');if(b){this.activeView=b.dataset.view;this.updateViewLabels();}};$('#viewport-labels').oncontextmenu=e=>{let b=e.target.closest('[data-view]');if(b){e.preventDefault();menu(['Perspective','Top','Front','Right'].map(name=>({label:name,action:()=>{this.activeView=name;this.four=false;this.updateViewLabels();this.invalidate();}})),e.clientX,e.clientY);}};}
  invalidate(){if(!this.ready||this.renderRequested)return;this.renderRequested=true;requestAnimationFrame(()=>{this.renderRequested=false;this.renderer.render(this.getViewports());this.drawOverlay();$('#render-stats').textContent=`${this.renderer.stats.triangles.toLocaleString()} tris · ${this.renderer.stats.frameMs.toFixed(1)} ms CPU`;});}
  rebuildScene(){if(!this.renderer||!this.ready)return;let entries=[];for(let o of [...this.doc.visibleObjects(),...this.previews])try{entries.push({object:o,display:this.doc.display(o)});}catch(e){this.log(`Geometry error (${o.name}): ${e.message}`);}let selection=new Set(this.doc.selection);if(this.selectedNode)for(let o of this.previews)if(o.nodeId===this.selectedNode)selection.add(o.id);this.renderer.setScene(entries,selection);this.invalidate();}
  updatePreviews(){let list=this.graph.previewGeometry(),next=new Map();this.previews=list.map((entry,i)=>{let key=entry.node.id+':'+i,stamp=this.graph.cache.get(entry.node.id)?.stamp??0,previous=this.previewMap.get(key);if(previous?.stamp===stamp){next.set(key,previous);return previous.object;}let color=entry.node.type==='ribs'?'#4c776e':'#77a595',o=makeObject(entry.geometry,entry.node.label,'weave',color);o.id='preview_'+key;o.preview=true;o.nodeId=entry.node.id;o.revision=stamp;o.material={roughness:.42,metallic:.18};next.set(key,{stamp,object:o});this.doc.cache.delete(o.id);return o;});for(let [key,value] of this.previewMap)if(!next.has(key))this.doc.cache.delete(value.object.id);this.previewMap=next;this.rebuildScene();}
  requestSolve(){if(!this.ready||this.solveRequested)return;this.solveRequested=true;requestAnimationFrame(()=>{this.solveRequested=false;try{this.graph.evaluate({document:this.doc,version:this.doc.version});this.graphView.refresh();this.updatePreviews();this.updateInspector();this.autosave();}catch(e){toast('Graph: '+e.message,true);}});}
  updateUI(){ $('#document-title').textContent=this.doc.name+'.veldra';document.title='Veldra 3D — '+this.doc.name;$('#document-object-count').textContent=this.doc.objects.length+' objects';$('#units-status').textContent=({mm:'Millimeters',cm:'Centimeters',m:'Meters',in:'Inches',ft:'Feet'})[this.doc.units];for(let [k,v] of Object.entries(this.flags))$('#toggle-'+k)?.classList.toggle('active',v);$('#selection-info').textContent=this.tool?this.toolPrompt():this.doc.selection.size?this.doc.selection.size+' selected'+(this.flags.points?' · Control points on':''):'';this.updateViewLabels();this.updateInspector();}
  setDisplay(mode){this.renderer.mode=mode;$('#display-label').textContent=MODES[mode];this.invalidate();}
  setView(name){this.activeView=name;this.four=false;this.updateViewLabels();this.invalidate();}
  toggleFour(){this.four=!this.four;if(this.four){let b=this.doc.bounds();for(let c of Object.values(this.cameras))if(c.type!=='Perspective')c.fit(b,1.4);}this.updateViewLabels();this.invalidate();}
  fit(selected){let b=selected&&this.doc.selection.size?this.doc.bounds(true):this.doc.bounds();if(!selected&&this.previews.length){let points=[b.min,b.max];for(let o of this.previews){let pb=this.doc.display(o).bounds;points.push(pb.min,pb.max);}let min=[0,1,2].map(i=>Math.min(...points.map(p=>p[i]))),max=[0,1,2].map(i=>Math.max(...points.map(p=>p[i])));b={min,max,center:V.mul(V.add(min,max),.5),size:V.sub(max,min)};}let vp=this.getViewports().find(v=>v.name===this.activeView)??this.getViewports()[0];vp.camera.fit(b,vp.width/vp.height);this.showCaption=false;this.updateViewLabels();this.invalidate();}
  toggle(name){this.flags[name]=!this.flags[name];if(name==='grid')this.renderer.grid=this.flags.grid;if(name==='points')this.selectedControl=null;this.updateUI();this.invalidate();}
  toggleWeave(){document.body.classList.toggle('weave-hidden');this.invalidate();if(!document.body.classList.contains('weave-hidden'))requestAnimationFrame(()=>this.graphView.fit());}
  setWorkspace(parametric){document.body.classList.remove('weave-hidden');document.body.classList.toggle('parametric-max',parametric);$('#model-workspace').classList.toggle('active',!parametric);$('#param-workspace').classList.toggle('active',parametric);requestAnimationFrame(()=>{this.graphView.fit();this.invalidate();});}
  autosave(){if(!this.ready)return;clearTimeout(this.autosaveTimer);this.autosaveTimer=setTimeout(()=>{try{let data=this.doc.serialize();data.extra.graph=this.graph.serialize();localStorage.setItem(STORAGE_KEY,JSON.stringify(data));$('.inspector-footer>span:last-child').innerHTML='<span class="autosave-dot"></span> Autosaved locally';}catch(e){$('.inspector-footer>span:last-child').textContent='Save file: autosave unavailable';}},450);}
  save(){let data=this.doc.serialize();data.extra.graph=this.graph.serialize();download(JSON.stringify(data,null,2),this.doc.name+'.veldra','application/json');this.log('Saved editable document and Weave definition.');toast('Document saved, including its parametric graph.');}
  openFile(){$('#file-input').click();}
  async importFile(file){if(file.size>100*1024*1024)throw Error('File exceeds the 100 MB import budget');let ext=file.name.split('.').pop().toLowerCase();if(['veldra','json','weave'].includes(ext)){let data=JSON.parse(await file.text());if(data.format==='weave'){this.graphView.snapshot();this.graph.restore(data);this.graphView.fit();}else{let testDoc=new Document(),testGraph=new Graph(COMPONENTS);testDoc.restore(data);testGraph.restore(data.extra?.graph??{format:'weave',version:1,nodes:[],wires:[]});this.doc.restore(data);this.doc.undoStack=[];this.doc.redoStack=[];this.graph.restore(data.extra?.graph??{format:'weave',version:1,nodes:[],wires:[]});this.showCaption=false;this.graphView.fit();this.requestSolve();}toast('Opened '+file.name);return;}
    let imported;if(ext==='obj')imported=importOBJ(await file.text());else if(ext==='stl')imported={mesh:importSTL(await file.arrayBuffer())};else if(ext==='dxf')imported=importDXF(await file.text());else throw Error('Supported inputs: .veldra, .weave, OBJ, STL, and basic DXF.');this.doc.transaction('Import '+file.name,()=>{let ids=[];if(imported.mesh)ids.push(this.doc.add(imported.mesh,file.name).id);if(imported.lines?.length)ids.push(this.doc.add({kind:'lines',segments:imported.lines},file.name+' lines').id);for(let c of imported.curves??[])ids.push(this.doc.add(c,file.name+' curve').id);this.doc.select(ids);});this.fit(true);this.showCaption=false;
  }
  async newDocument(){let v=await formDialog('New document',[{key:'name',label:'Name',value:'Untitled',type:'text'}],{description:'Save your current document first to keep a separate copy. Creating a new document replaces the current autosaved workspace.',submit:'Create document'});if(!v)return;let d=new Document();d.name=v.name;this.doc.restore(d.serialize());this.doc.undoStack=[];this.doc.redoStack=[];this.graph.restore({format:'weave',version:1,nodes:[],wires:[]});this.graphView.select(null);this.showCaption=false;this.requestSolve();this.fit(false);}
  async loadDemo(){let v=await formDialog('Open canopy study',[],{description:'This replaces the current workspace. Save the current document first to retain a separate copy.',submit:'Open example'});if(!v)return;let currentDoc=this.doc,currentGraph=this.graph;this.setupDemoData();let data=this.doc.serialize(),graphData=this.graph.serialize();this.doc=currentDoc;this.graph=currentGraph;this.commands=new Commands(this);this.doc.restore(data);this.graph.restore(graphData);this.doc.undoStack=[];this.doc.redoStack=[];this.showCaption=true;this.cameras.Perspective=new Camera();this.graphView.select(null);this.graphView.fit();this.requestSolve();}
  bake(){try{let outputs=this.graph.previewGeometry();if(this.selectedNode){let selected=outputs.filter(e=>e.node.id===this.selectedNode);if(selected.length)outputs=selected;}if(!outputs.length)throw Error('Enable preview on a geometry-producing component first');let graphBefore=this.graph.serialize();this.doc.transaction('Bake Weave geometry',()=>{let layer=this.doc.layers.find(l=>l.id==='baked');if(!layer){layer={id:'baked',name:'Weave / baked',color:'#6f9b8c',visible:true,locked:false};this.doc.layers.push(layer);}let ids=outputs.map(e=>this.doc.add(structuredClone(e.geometry),e.node.label+' / baked',{layer:'baked',color:e.node.type==='ribs'?'#4c776e':'#77a595'}).id);this.doc.select(ids);});for(let {node} of outputs)node.preview=false;let history=this.doc.undoStack.at(-1);history.graphBefore=graphBefore;history.graphAfter=this.graph.serialize();this.graph.changed('preview');this.graphView.select(null);toast(`Baked ${outputs.length} editable objects. Their graph previews are now hidden.`);}catch(e){toast(e.message,true);}}
  exportEntries(){let objects=this.doc.selection.size?this.doc.selected():[...this.doc.visibleObjects(),...this.previews];return objects.map(o=>({name:o.name,layer:o.layer,...this.doc.display(o)}));}
  async capture(){this.renderer.render(this.getViewports());await this.renderer.device?.queue?.onSubmittedWorkDone?.();let canvas=document.createElement('canvas');canvas.width=this.renderer.canvas.width;canvas.height=this.renderer.canvas.height;let ctx=canvas.getContext('2d');ctx.drawImage(this.renderer.canvas,0,0);ctx.drawImage($('#overlay-canvas'),0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(blob)download(blob,this.doc.name+'.png','image/png');});}
  installViewEvents(){
    let area=$('#viewport-area');this.touches=new Map();const position=e=>{let r=area.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top];};
    area.addEventListener('pointerdown',e=>{
      if(e.target.closest('.viewport-toolbar,.viewport-label'))return;closePopups();area.focus();let [x,y]=position(e),view=this.viewAt(x,y);this.activeView=view.name;if(this.tool&&!this.tool.points.length)this.tool.view=view.name;this.touches.set(e.pointerId,[x,y]);area.setPointerCapture(e.pointerId);
      if(this.touches.size===2){let pts=[...this.touches.values()];this.pinch={distance:Math.hypot(pts[1][0]-pts[0][0],pts[1][1]-pts[0][1]),radius:view.camera.radius,scale:view.camera.scale,center:V.mix(pts[0],pts[1],.5),view};this.pointer=null;return;}
      this.pointer={x,y,lastX:x,lastY:y,view,button:e.button,mode:e.button===2||e.pointerType==='touch'&&!this.tool?'orbit':e.button===1||e.shiftKey&&!this.tool?'pan':this.tool?'draw':'select',moved:false};
      if(e.button===0&&!this.tool){let cp=this.controlHandles.find(h=>h.view===view.name&&Math.hypot(x-h.screen[0],y-h.screen[1])<9);if(cp){this.selectedControl=cp;this.pointer.mode='control';this.pointer.handle=cp;this.pointer.before=this.doc.serialize();this.pointer.selection=[...this.doc.selection];this.pointer.startPoint=this.rayPlane(view,x,y,cp.world,V.unit(V.sub(view.camera.eye,view.camera.target)));this.pointer.normal=V.unit(V.sub(view.camera.eye,view.camera.target));this.updateInspector();}
        else{let handle=this.gumballHandles.find(h=>h.view===view.name&&segmentDistance([x,y],h.a,h.b)<7);if(handle){this.pointer.mode='gumball';this.pointer.handle=handle;this.pointer.before=this.doc.serialize();this.pointer.selection=[...this.doc.selection];this.pointer.transforms=this.doc.selected().map(o=>({o,matrix:[...o.matrix]}));}}
      }
      e.preventDefault();
    });
    area.addEventListener('pointermove',e=>{let [x,y]=position(e);if(this.touches.has(e.pointerId))this.touches.set(e.pointerId,[x,y]);if(this.pinch&&this.touches.size===2){let pts=[...this.touches.values()],distance=Math.hypot(pts[1][0]-pts[0][0],pts[1][1]-pts[0][1]),center=V.mix(pts[0],pts[1],.5),camera=this.pinch.view.camera;camera.radius=clamp(this.pinch.radius*this.pinch.distance/Math.max(10,distance),.1,1e7);camera.scale=clamp(this.pinch.scale*this.pinch.distance/Math.max(10,distance),.01,1e7);camera.pan(center[0]-this.pinch.center[0],center[1]-this.pinch.center[1],this.pinch.view.height);this.pinch.center=center;this.invalidate();return;}
      let view=this.pointer?.view??this.viewAt(x,y),point=view.camera.planePoint(x-view.x,y-view.y,view.width,view.height);if(point){if(this.tool)point=this.snap(point,x,y,view);this.hoverPoint=point;$('#coordinates').innerHTML=`X ${point[0].toFixed(3)} <span>Y ${point[1].toFixed(3)}</span> Z ${point[2].toFixed(3)}`;}
      let p=this.pointer;if(p){let dx=x-p.lastX,dy=y-p.lastY;p.lastX=x;p.lastY=y;if(Math.hypot(x-p.x,y-p.y)>3)p.moved=true;
        if(p.mode==='orbit'){p.view.camera.orbit(dx,dy);this.showCaption=false;}
        else if(p.mode==='pan'){p.view.camera.pan(dx,dy,p.view.height);this.showCaption=false;}
        else if(p.mode==='gumball'){let h=p.handle,screenDelta=[x-p.x,y-p.y],axis=[h.b[0]-h.a[0],h.b[1]-h.a[1]],amount=(screenDelta[0]*axis[0]+screenDelta[1]*axis[1])/(axis[0]**2+axis[1]**2)*h.length;if(this.flags.snap)amount=Math.round(amount);for(let item of p.transforms){item.o.matrix=M.mul(M.translation(V.mul(h.axis,amount)),item.matrix);this.doc.touch(item.o);}this.doc.notify('drag');}
        else if(p.mode==='control'){let h=p.handle,now=this.rayPlane(view,x,y,h.world,p.normal);if(now&&p.startPoint){let world=V.add(h.world,V.sub(now,p.startPoint));if(this.flags.snap)world=world.map(Math.round);let local=M.point(M.inverse(h.object.matrix),world);if(h.row!==undefined)h.object.geometry.points[h.row][h.column]=local;else h.object.geometry.points[h.index]=local;this.doc.touch(h.object);this.doc.notify('drag');}}
      }
      this.invalidate();
    });
    area.addEventListener('pointerup',e=>{let [x,y]=position(e);this.touches.delete(e.pointerId);if(this.pinch){if(this.touches.size<2)this.pinch=null;this.pointer=null;return;}let p=this.pointer;this.pointer=null;if(!p)return;if((p.mode==='gumball'||p.mode==='control')&&p.moved){this.doc.undoStack.push({label:p.mode==='control'?'Edit control point':'Gumball move',data:p.before,selection:p.selection});this.doc.redoStack=[];this.doc.notify('Transform');this.updateInspector(true);}else if(p.mode==='draw'&&!p.moved){let point=p.view.camera.planePoint(x-p.view.x,y-p.view.y,p.view.width,p.view.height);if(point)this.addToolPoint(this.snap(point,x,y,p.view));}
      else if(p.mode==='select'){if(p.moved){let left=Math.min(x,p.x),right=Math.max(x,p.x),top=Math.min(y,p.y),bottom=Math.max(y,p.y),ids=[];for(let o of this.doc.visibleObjects()){let b=this.doc.display(o).bounds;if(!b.center.every(Number.isFinite))continue;let c=p.view.camera.project(b.center,p.view.width,p.view.height);if(c[0]+p.view.x>=left&&c[0]+p.view.x<=right&&c[1]+p.view.y>=top&&c[1]+p.view.y<=bottom)ids.push(o.id);}this.graphView.select(null);this.doc.select(ids,e.ctrlKey||e.metaKey);}else this.pick(x,y,p.view,e.ctrlKey||e.metaKey);}
      else if(p.mode==='orbit'&&!p.moved&&e.pointerType!=='touch'){menu((this.doc.selection.size?['move','rotate','scale','duplicate','delete',null,'zoomselected','analyze']:['curve','circle','box','surface',null,'zoomextents','fourview','weave']).map(id=>id?{...this.commands.items.get(id),action:()=>this.run(id)}:null),e.clientX,e.clientY);}else if(p.mode==='orbit'&&!p.moved&&e.pointerType==='touch')this.pick(x,y,p.view,false);this.updateViewLabels();this.invalidate();
    });
    area.addEventListener('pointercancel',e=>{this.touches.delete(e.pointerId);let p=this.pointer;if(p?.before)this.doc.restore(p.before,'cancel');this.pointer=null;this.pinch=null;this.invalidate();});
    area.addEventListener('contextmenu',e=>e.preventDefault());area.addEventListener('wheel',e=>{e.preventDefault();let [x,y]=position(e);this.viewAt(x,y).camera.zoom(e.deltaY);this.invalidate();},{passive:false});area.addEventListener('dblclick',e=>{if(this.tool&&['curve','interpcurve','polyline'].includes(this.tool.type))this.finishTool();});
  }
  rayPlane(view,x,y,origin,normal){let r=view.camera.ray(x-view.x,y-view.y,view.width,view.height),den=V.dot(r.direction,normal);return Math.abs(den)<1e-10?null:V.add(r.origin,V.mul(r.direction,V.dot(V.sub(origin,r.origin),normal)/den));}
  pick(x,y,view,additive){let ray=view.camera.ray(x-view.x,y-view.y,view.width,view.height),hit=this.doc.pickRay(ray.origin,ray.direction);let curveHit=null,bestScreen=8;
    for(let o of this.doc.visibleObjects()){if(o.locked||this.doc.layers.find(l=>l.id===o.layer)?.locked)continue;let d=this.doc.display(o);for(let segment of d.lines){let a=view.camera.project(segment[0],view.width,view.height),b=view.camera.project(segment[1],view.width,view.height);if(a[2]<0||a[2]>1||b[2]<0||b[2]>1)continue;let distance=segmentDistance([x-view.x,y-view.y],a,b);if(distance<bestScreen){bestScreen=distance;curveHit=o;}}}
    if(curveHit){this.graphView.select(null);if(additive&&this.doc.selection.has(curveHit.id)){this.doc.selection.delete(curveHit.id);this.doc.notify('selection');}else this.doc.select([curveHit.id],additive);return;}
    let previewHit=null;for(let o of this.previews){let d=this.doc.display(o);if(!d.mesh?.indices.length)continue;d.bvh??=new MeshBVH(d.mesh);let h=d.bvh.intersect(ray.origin,ray.direction);if(h&&(!previewHit||h.t<previewHit.t))previewHit={...h,object:o};}
    if(previewHit&&(!hit||previewHit.t<hit.t-.0001)){this.doc.select([]);this.graphView.select(previewHit.object.nodeId);this.panel='properties';this.updateInspector(true);return;}
    this.selectedControl=null;this.graphView.select(null);if(hit){if(additive&&this.doc.selection.has(hit.object.id)){this.doc.selection.delete(hit.object.id);this.doc.notify('selection');}else this.doc.select([hit.object.id],additive);}else this.doc.select([]);this.panel='properties';this.updateInspector(true);
  }
  snap(point,x,y,view){this.snapPoint=null;this.snapLabel='';let p=[...point];if(this.flags.snap)p=p.map(Math.round);if(this.flags.ortho&&this.tool?.points.length){let base=this.tool.points.at(-1),axes=view.name==='Front'?[0,2]:view.name==='Right'?[1,2]:[0,1],a=axes[0],b=axes[1];if(Math.abs(p[a]-base[a])>Math.abs(p[b]-base[b]))p[b]=base[b];else p[a]=base[a];}
    if(this.flags.osnap){let candidates=[];for(let o of this.doc.visibleObjects()){let g=o.geometry;if(g.kind==='curve'){let c=NurbsCurve.from(g);for(let [t,label] of [[0,'End'],[.5,'Mid'],[1,'End']])candidates.push({point:M.point(o.matrix,c.at(t)),label});if(g.degree===1)for(let q of g.points)candidates.push({point:M.point(o.matrix,q),label:'Point'});}else if(g.kind==='point')candidates.push({point:M.point(o.matrix,g.point),label:'Point'});else{let b=this.doc.display(o).bounds;if(b.center.every(Number.isFinite))candidates.push({point:b.center,label:'Center'});}}
      let best=11;for(let c of candidates){let q=view.camera.project(c.point,view.width,view.height),d=Math.hypot(q[0]+view.x-x,q[1]+view.y-y);if(q[2]>0&&q[2]<1&&d<best){best=d;p=c.point;this.snapPoint=p;this.snapLabel=c.label;}}
    }return p;
  }
  beginTool(type){this.graphView.select(null);this.tool={type,points:[],view:this.activeView};this.hoverPoint=null;this.selectedControl=null;this.doc.select([]);this.showCaption=false;this.log(this.toolPrompt());this.updateUI();$('#viewport-area').style.cursor='crosshair';this.invalidate();}
  toolPrompt(){if(!this.tool)return '';let n=this.tool.points.length;return ({point:'Point: click to place. Esc finishes.',line:n?'Line: pick endpoint.':'Line: pick start point.',polyline:`Polyline: ${n} points. Pick next; Enter finishes.`,curve:`Curve: ${n} control points. Pick next; Enter finishes.`,interpcurve:`Interpolated curve: ${n} points. Enter finishes.`,circle:n?'Circle: pick radius point.':'Circle: pick center.',rectangle:n?'Rectangle: pick opposite corner.':'Rectangle: pick first corner.',distance:n?'Distance: pick second point.':'Distance: pick first point.'})[this.tool.type]??'';}
  addToolPoint(point){if(!this.tool)return;let t=this.tool;if(t.points.length&&V.distance(point,t.points.at(-1))<1e-9)return;t.points.push([...point]);if(t.type==='point'){this.commands.addGeometry({kind:'point',point},'Point');t.points=[];}else if(['line','circle','rectangle','distance'].includes(t.type)&&t.points.length===2)this.finishTool();this.updateUI();this.invalidate();}
  planeBasis(name){if(name==='Front')return M.rotation([1,0,0],Math.PI/2);if(name==='Right')return [0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1];return M.identity();}
  toolGeometry(points){let type=this.tool.type;if(points.length<2)return null;if(type==='line'||type==='polyline'||type==='distance')return polyline(points);if(type==='curve')return new NurbsCurve(points,Math.min(3,points.length-1)).toJSON();if(type==='interpcurve')return interpolateCurve(points,Math.min(3,points.length-1)).toJSON();if(type==='circle'){let radius=V.distance(points[0],points.at(-1));if(radius<1e-8)return null;return transformGeometry(circleCurve([0,0,0],radius).toJSON(),M.mul(M.translation(points[0]),this.planeBasis(this.tool.view)));}if(type==='rectangle'){let basis=this.planeBasis(this.tool.view),inv=M.inverse(basis),a=M.point(inv,points[0]),b=M.point(inv,points.at(-1)),local=[[a[0],a[1],a[2]],[b[0],a[1],a[2]],[b[0],b[1],a[2]],[a[0],b[1],a[2]]];return transformGeometry(polyline(local,true),basis);}return null;}
  finishTool(){if(!this.tool)return;try{let t=this.tool;if(t.points.length<2){this.cancelTool();return;}if(t.type==='distance'){let distance=V.distance(t.points[0],t.points[1]);this.log(`Distance: ${distance.toFixed(6)} ${this.doc.units}`);toast(`Distance: ${distance.toFixed(4)} ${this.doc.units}`);}else{let g=this.toolGeometry(t.points);if(g)this.commands.addGeometry(g,({curve:'NURBS curve',interpcurve:'Interpolated curve',circle:'Circle',rectangle:'Rectangle',polyline:'Polyline',line:'Line'})[t.type]??t.type);}this.cancelTool();}catch(e){toast(e.message,true);}}
  cancelTool(){this.tool=null;this.hoverPoint=null;this.snapPoint=null;$('#viewport-area').style.cursor='default';this.updateUI();this.invalidate();}
  drawOverlay(){let canvas=$('#overlay-canvas'),area=$('#viewport-area'),ratio=Math.min(devicePixelRatio||1,2),w=area.clientWidth,h=area.clientHeight;canvas.width=Math.max(1,Math.round(w*ratio));canvas.height=Math.max(1,Math.round(h*ratio));let ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);this.controlHandles=[];this.gumballHandles=[];ctx.font='10px Segoe UI,Arial';
    for(let view of this.getViewports()){ctx.save();ctx.beginPath();ctx.rect(view.x,view.y,view.width,view.height);ctx.clip();const project=p=>{let q=view.camera.project(p,view.width,view.height);return [q[0]+view.x,q[1]+view.y,q[2]];};
      // World-axis triad, projected from the camera orientation but fixed in the viewport corner.
      let center=[view.x+42,view.y+view.height-48],cam=view.camera,target=cam.target,base=cam.project(target,view.width,view.height),axisSize=cam.type==='Perspective'?cam.radius*.065:cam.scale*.1;
      for(let [axis,color,label] of [[[1,0,0],'#b76663','X'],[[0,1,0],'#679478','Y'],[[0,0,1],'#688eac','Z']]){let q=cam.project(V.add(target,V.mul(axis,axisSize)),view.width,view.height),dx=q[0]-base[0],dy=q[1]-base[1],length=Math.hypot(dx,dy),scale=28/Math.max(28,length);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(...center);ctx.lineTo(center[0]+dx*scale,center[1]+dy*scale);ctx.stroke();ctx.fillText(label,center[0]+dx*scale+3,center[1]+dy*scale-2);}
      if(this.flags.points)for(let o of this.doc.selected()){let g=o.geometry;if(!['curve','surface'].includes(g.kind))continue;let rows=g.kind==='curve'?[g.points]:g.points;ctx.strokeStyle='#889599';ctx.lineWidth=.7;ctx.setLineDash([3,3]);for(let row of rows){ctx.beginPath();row.forEach((p,i)=>{let q=project(M.point(o.matrix,p));if(i)ctx.lineTo(q[0],q[1]);else ctx.moveTo(q[0],q[1]);});ctx.stroke();}if(g.kind==='surface')for(let i=0;i<rows[0].length;i++){ctx.beginPath();rows.forEach((r,j)=>{let q=project(M.point(o.matrix,r[i]));if(j)ctx.lineTo(q[0],q[1]);else ctx.moveTo(q[0],q[1]);});ctx.stroke();}ctx.setLineDash([]);rows.forEach((row,r)=>row.forEach((p,i)=>{let world=M.point(o.matrix,p),screen=project(world);if(screen[2]<0||screen[2]>1)return;let handle={object:o,world,screen,view:view.name,...(g.kind==='curve'?{index:i}:{row:r,column:i})};this.controlHandles.push(handle);let selected=this.selectedControl?.object.id===o.id&&this.selectedControl?.index===handle.index&&this.selectedControl?.row===handle.row&&this.selectedControl?.column===handle.column;ctx.fillStyle=selected?'#dc992f':'#fff';ctx.strokeStyle='#467c70';ctx.lineWidth=1.1;ctx.fillRect(screen[0]-3,screen[1]-3,6,6);ctx.strokeRect(screen[0]-3,screen[1]-3,6,6);}));}
      if(this.flags.gumball&&this.doc.selection.size&&!this.flags.points&&!this.tool){let b=this.doc.bounds(true),center=b.center,worldLength=cam.type==='Perspective'?cam.radius*.115:cam.scale*.17,a=project(center);if(a[2]>0&&a[2]<1)for(let [axis,color,label] of [[[1,0,0],'#c86c63','X'],[[0,1,0],'#639675','Y'],[[0,0,1],'#668bb7','Z']]){let end=project(V.add(center,V.mul(axis,worldLength))),dx=end[0]-a[0],dy=end[1]-a[1],length=Math.hypot(dx,dy);if(length<9)continue;let b2=[end[0],end[1]],a2=[a[0],a[1]];this.gumballHandles.push({axis,a:a2,b:b2,length:worldLength,view:view.name});ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(...a2);ctx.lineTo(...b2);ctx.stroke();let ux=dx/length,uy=dy/length;ctx.beginPath();ctx.moveTo(...b2);ctx.lineTo(b2[0]-ux*9-uy*4,b2[1]-uy*9+ux*4);ctx.lineTo(b2[0]-ux*9+uy*4,b2[1]-uy*9-ux*4);ctx.fill();ctx.fillText(label,b2[0]+5,b2[1]-6);}ctx.fillStyle='#f8f8f3';ctx.strokeStyle='#d4a33f';ctx.lineWidth=2;ctx.fillRect(a[0]-3,a[1]-3,6,6);ctx.strokeRect(a[0]-3,a[1]-3,6,6);}
      if(this.tool&&this.tool.view===view.name){let points=[...this.tool.points];if(this.hoverPoint)points.push(this.hoverPoint);let geometry;try{geometry=this.toolGeometry(points);}catch{}ctx.strokeStyle='#ad7b34';ctx.lineWidth=1.5;ctx.setLineDash([5,3]);if(geometry?.kind==='curve'){let samples=NurbsCurve.from(geometry).sample(90);ctx.beginPath();samples.forEach((p,i)=>{let q=project(p);if(i)ctx.lineTo(q[0],q[1]);else ctx.moveTo(q[0],q[1]);});ctx.stroke();}ctx.setLineDash([]);for(let p of this.tool.points){let q=project(p);ctx.fillStyle='#ad7b34';ctx.fillRect(q[0]-3,q[1]-3,6,6);}if(this.snapPoint){let p=project(this.snapPoint);ctx.strokeStyle='#bc873a';ctx.lineWidth=1;ctx.strokeRect(p[0]-5,p[1]-5,10,10);ctx.fillStyle='#866027';ctx.fillText(this.snapLabel,p[0]+9,p[1]-7);}}
      ctx.restore();
    }
    if(this.pointer?.mode==='select'&&this.pointer.moved){let p=this.pointer;ctx.setLineDash([5,3]);ctx.strokeStyle='#3c8270';ctx.fillStyle='#528f7910';ctx.fillRect(p.x,p.y,p.lastX-p.x,p.lastY-p.y);ctx.strokeRect(p.x,p.y,p.lastX-p.x,p.lastY-p.y);ctx.setLineDash([]);}
  }
  updateInspector(force=false){
    if(!this.graphView)return;let content=$('#inspector-content');if(!force&&content.contains(document.activeElement)&&document.activeElement.matches('input,select,textarea'))return;
    for(let b of $$('#inspector-tabs button'))b.classList.toggle('active',b.dataset.panel===this.panel);
    const section=(title,body,extra='')=>`<section class="inspector-section"><div class="section-title">${title}${extra}</div>${body}</section>`;
    const node=this.graph.nodes.find(n=>n.id===this.selectedNode),selected=this.doc.selected(),object=selected.length===1?selected[0]:null;
    const layerRows=()=>`<div class="layer-header"><span>NAME</span><span>VISIBLE &nbsp; LOCK</span></div>${this.doc.layers.map(l=>`<div class="layer-row ${this.doc.currentLayer===l.id?'active':''}" data-layer="${l.id}"><span class="layer-check" title="Set current layer" data-current-layer="${l.id}">${this.doc.currentLayer===l.id?'✓':''}</span><span class="color-dot" style="background:${escape(l.color)}"></span><span class="layer-name" data-layer-name="${l.id}">${escape(l.name)}</span><button data-layer-toggle="visible" data-layer-id="${l.id}" class="${l.visible?'':'off'}" title="Toggle layer visibility">${icon('eye')}</button><button data-layer-toggle="locked" data-layer-id="${l.id}" class="${l.locked?'':'off'}" title="Toggle layer locking">${icon('lock')}</button></div>`).join('')}`;
    if(this.panel==='layers')content.innerHTML=`<div class="inspector-hero"><span class="eyebrow">DOCUMENT ORGANIZATION</span><h2>Layers</h2><p>Keep your model structured. Double-click a layer name to rename it.</p></div>`+section('Model layers',layerRows(),'<button data-command="layer" title="Add layer">+</button>')+section('Selection',`<p class="inspector-note">${selected.length} selected objects</p><select id="assign-layer" style="width:100%;margin-top:8px"><option value="">Move selection to layer…</option>${this.doc.layers.map(l=>`<option value="${l.id}">${escape(l.name)}</option>`).join('')}</select>`);
    else if(this.panel==='objects')content.innerHTML=`<div class="inspector-hero"><span class="eyebrow">SCENE EXPLORER</span><h2>Objects <span class="muted">/ ${this.doc.objects.length}</span></h2><p>Select an object to inspect it. Ctrl-click in the viewport adds to selection.</p></div>${this.doc.objects.map(o=>`<div class="object-row ${this.doc.selection.has(o.id)?'selected':''}" data-object-select="${o.id}">${icon(o.geometry.kind==='curve'?'curve':o.geometry.kind==='surface'?'surface':'box')}<span>${escape(o.name)}<br><small>${escape(o.geometry.kind)}</small></span><button data-object-visible="${o.id}" title="Toggle visibility" style="opacity:${o.visible?1:.35}">${icon('eye')}</button></div>`).join('')}`+section('Live preview',`<p class="inspector-note">${this.previews.length} Weave outputs. Bake the graph to create independently editable model objects.</p><div class="inspector-actions"><button data-command="bake">Bake geometry</button></div>`);
    else if(this.panel==='materials'){
      content.innerHTML=`<div class="inspector-hero"><span class="eyebrow">SURFACE APPEARANCE</span><h2>Materials</h2><p>Physically based metallic / roughness shading.</p></div>`+(object?section(escape(object.name),`<div class="material-preview"><div class="material-ball" style="--ball-color:${escape(object.color)}"></div></div><div class="property-grid"><label>Base color</label><input type="color" data-object-color value="${escape(object.color)}"><label>Roughness</label><input type="number" min="0.04" max="1" step="0.01" data-material="roughness" value="${object.material.roughness}"><label>Metallic</label><input type="number" min="0" max="1" step="0.01" data-material="metallic" value="${object.material.metallic}"></div><div class="inspector-actions"><button data-command="rendered">Rendered view</button></div>`):section('No object selected','<p class="inspector-note">Select one document object to edit its material. Bake live graph geometry before assigning a document material.</p>'));
    }else if(node){
      let def=this.graph.registry[node.type],cached=this.graph.cache.get(node.id);content.innerHTML=`<div class="inspector-hero"><span class="eyebrow">WEAVE / ${escape(def.category.toUpperCase())}</span><h2>${escape(node.label)}</h2><p>${escape(def.name)} component</p><div class="tags"><span class="tag green">${cached?.error?'Needs attention':'Solved'}</span><span class="tag">${(cached?.time??0).toFixed(2)} ms</span><span class="tag">${def.outputs.length} outputs</span></div></div>`;
      let controls=`<div class="property-grid"><label>Label</label><input data-node-label value="${escape(node.label)}"></div>`;
      if(node.type==='number')controls+=`<div class="parameter"><div class="parameter-label">Value <output>${node.params.value}</output></div><input type="range" data-node-value min="${node.params.min}" max="${node.params.max}" step="${node.params.step}" value="${node.params.value}"></div><div class="property-grid" style="margin-top:15px">${['value','min','max','step'].map(k=>`<label>${k[0].toUpperCase()+k.slice(1)}</label><input type="number" step="any" data-node-property="${k}" value="${node.params[k]}">`).join('')}</div>`;
      else if(node.type==='reference')controls+=`<label class="dialog-field" style="margin-top:12px"><span>Referenced object</span><select data-node-property="objectId">${this.doc.objects.map(o=>`<option value="${o.id}" ${o.id===node.params.objectId?'selected':''}>${escape(o.name)}</option>`).join('')}</select></label>`;
      else controls+=`<div class="property-grid" style="margin-top:15px">${def.inputs.map((p,i)=>{let connected=this.graph.wires.some(w=>w.to===node.id&&w.input===i),value=node.params[p.key]??p.default;if(connected)return `<label>${escape(p.name)}</label><span class="tag green">Connected</span>`;if(p.type==='number')return `<label>${escape(p.name)}</label><input type="number" step="any" data-node-input="${i}" value="${value??''}">`;if(['point','vector'].includes(p.type))return `<label>${escape(p.name)}</label><input data-node-input="${i}" value="${Array.isArray(value)?value.join(', '):'0, 0, 0'}">`;return `<label>${escape(p.name)}</label><span class="muted">Connect ${escape(p.type)}</span>`;}).join('')}</div>`;
      content.innerHTML+=section('Component settings',controls)+section('Output',`<div class="property-grid"><label>Preview</label><button class="secondary" data-node-preview>${node.preview?'Visible':'Hidden'}</button><label>Status</label><span>${escape(cached?.error??'Valid')}</span></div><div class="inspector-actions"><button data-command="bake">Bake output</button><button id="delete-node">Delete</button></div><p class="inspector-note">Drag output ports onto compatible inputs. Cached components only recalculate when their inputs change.</p>`);
    }else if(object){
      let g=object.geometry,d=this.doc.display(object),b=d.bounds,type=({curve:'NURBS curve',surface:'NURBS surface',extrusion:'Profile extrusion',mesh:'Polygon mesh',box:'Parametric box',sphere:'Parametric sphere',cylinder:'Parametric cylinder',torus:'Parametric torus'})[g.kind]??g.kind;
      content.innerHTML=`<div class="inspector-hero"><span class="eyebrow">OBJECT PROPERTIES</span><h2>${escape(object.name)}</h2><p>${escape(type)}</p><div class="tags"><span class="tag green">Editable</span><span class="tag">${this.doc.units}</span>${g.kind==='surface'||g.kind==='curve'?'<span class="tag">Double precision</span>':''}</div></div>`;
      content.innerHTML+=section('Attributes',`<div class="property-grid"><label>Name</label><input data-object-name value="${escape(object.name)}"><label>Layer</label><select data-object-layer>${this.doc.layers.map(l=>`<option value="${l.id}" ${object.layer===l.id?'selected':''}>${escape(l.name)}</option>`).join('')}</select><label>Color</label><input type="color" data-object-color value="${escape(object.color)}"></div>`);
      content.innerHTML+=section('World translation',`<div class="vector-input">${['X','Y','Z'].map((a,i)=>`<label><span>${a}</span><input type="number" step="0.1" data-position="${i}" value="${Number(object.matrix[12+i].toFixed(4))}"></label>`).join('')}</div><p class="inspector-note">Drag the colored gumball axes to move in world coordinates.</p>`);
      let parameters=Object.entries(g).filter(([k,v])=>typeof v==='number'&&!['degree','degreeU','degreeV'].includes(k));if(parameters.length)content.innerHTML+=section('Geometry parameters',`<div class="property-grid">${parameters.map(([k,v])=>`<label>${escape(k[0].toUpperCase()+k.slice(1))}</label><input type="number" step="0.1" min="0.001" data-geometry-param="${k}" value="${v}">`).join('')}</div>`);
      if(g.kind==='curve')content.innerHTML+=section('Curve definition',`<div class="property-grid"><span>Degree</span><span>${g.degree}</span><span>Control points</span><span>${g.points.length}</span><span>Knots</span><span>${g.knots.length}</span><span>Rational</span><span>${g.weights.some(w=>Math.abs(w-1)>1e-9)?'Yes':'No'}</span></div><div class="inspector-actions"><button data-command="points">${this.flags.points?'Hide':'Edit'} points</button><button data-command="insertknot">Insert knot</button></div>`);
      if(g.kind==='surface')content.innerHTML+=section('Surface definition',`<div class="property-grid"><span>Degree U / V</span><span>${g.degreeU} / ${g.degreeV}</span><span>Control net</span><span>${g.points[0].length} × ${g.points.length}</span><span>Display mesh</span><span>${d.mesh.indices.length/3} triangles</span></div><div class="inspector-actions"><button data-command="points">${this.flags.points?'Hide':'Edit'} points</button><button data-command="gpuevaluate">GPU evaluate</button></div>`);
      if(b.size.every(Number.isFinite))content.innerHTML+=section('Bounding box',`<div class="property-grid">${['X','Y','Z'].map((a,i)=>`<span>Size ${a}</span><span>${b.size[i].toFixed(3)} ${this.doc.units}</span>`).join('')}</div><div class="inspector-actions"><button data-command="analyze">Analyze</button><button data-command="zoomselected">Frame selection</button></div>`);
    }else if(selected.length>1){content.innerHTML=`<div class="inspector-hero"><span class="eyebrow">MULTIPLE SELECTION</span><h2>${selected.length} objects</h2><p>Transforms and supported modeling operations apply to the selected objects.</p></div>`+section('Modeling',`<div class="inspector-actions"><button data-command="loft">Loft</button><button data-command="union">Mesh union</button></div><div class="inspector-actions"><button data-command="move">Move</button><button data-command="array">Array</button><button data-command="analyze">Analyze</button></div>`)+section('Layers',layerRows());}
    else{
      let params=this.graph.nodes.filter(n=>n.type==='number').slice(0,4);content.innerHTML=`<div class="inspector-hero"><span class="eyebrow">${this.showCaption?'PARAMETRIC EXPLORATION / 001':'MODEL WORKSPACE'}</span><h2>${this.showCaption?'Canopy study':escape(this.doc.name)}</h2><p>${this.showCaption?'A continuous surface. A responsive structure. An idea you can shape.':'Precision geometry and visual algorithms, in one workspace.'}</p><div class="tags"><span class="tag green">${this.graph.enabled?'Live definition':'Solver paused'}</span><span class="tag">NURBS</span><span class="tag">${this.doc.units}</span></div></div>`;
      if(params.length)content.innerHTML+=section('Design parameters',params.map(n=>`<div class="parameter"><div class="parameter-label"><label>${escape(n.label)}</label><output data-param-output="${n.id}">${n.params.value}</output></div><input type="range" data-param-node="${n.id}" min="${n.params.min}" max="${n.params.max}" step="${n.params.step}" value="${n.params.value}" aria-label="${escape(n.label)}"><div class="parameter-endpoints"><span>${n.params.min}</span><span>${n.params.max}</span></div></div>`).join(''),'<span>LIVE INPUTS</span>');
      content.innerHTML+=section('Layers',layerRows(),'<button data-command="layer" title="Add layer">+</button>')+section('Document',`<div class="stat-grid"><div class="stat-item"><div class="value">${this.doc.objects.length+this.previews.length}</div><div class="label">VISIBLE + LIVE OBJECTS</div></div><div class="stat-item"><div class="value">${this.graph.solveTime.toFixed(1)}<span style="font-size:10px;color:var(--muted)"> ms</span></div><div class="label">LAST GRAPH SOLUTION</div></div></div><p class="inspector-note">${this.doc.tolerance} ${this.doc.units} absolute tolerance<br>Click a surface to inspect its generating component.</p>`);
    }
    this.bindInspector(object,node);
  }
  bindInspector(object,node){let root=$('#inspector-content');root.onclick=e=>{let b=e.target.closest('[data-object-select]');if(b&&!e.target.closest('[data-object-visible]')){this.graphView.select(null);this.doc.select([b.dataset.objectSelect],e.ctrlKey||e.metaKey);return;}let visible=e.target.closest('[data-object-visible]');if(visible){this.doc.transaction('Visibility',()=>{let o=this.doc.get(visible.dataset.objectVisible);o.visible=!o.visible;});return;}let layer=e.target.closest('[data-layer-toggle]');if(layer){this.doc.transaction('Layer '+layer.dataset.layerToggle,()=>{let l=this.doc.layers.find(l=>l.id===layer.dataset.layerId);l[layer.dataset.layerToggle]=!l[layer.dataset.layerToggle];});return;}let current=e.target.closest('[data-current-layer]');if(current){this.doc.currentLayer=current.dataset.currentLayer;this.updateInspector(true);this.autosave();return;}if(e.target.closest('[data-node-preview]')&&node){this.graphView.edit(()=>{node.preview=!node.preview;this.graph.changed('preview');});this.updateInspector(true);}if(e.target.closest('#delete-node')&&node)this.graphView.edit(()=>{this.graph.remove(node.id);this.graphView.select(null);});};
    root.ondblclick=async e=>{let target=e.target.closest('[data-layer-name]');if(target){let layer=this.doc.layers.find(l=>l.id===target.dataset.layerName),p=await formDialog('Rename layer',[{key:'name',label:'Layer name',value:layer.name,type:'text'},{key:'color',label:'Layer color',value:layer.color,type:'color'}],{submit:'Apply'});if(p)this.doc.transaction('Edit layer',()=>Object.assign(layer,p));}};
    root.onpointerdown=e=>{if(e.target.matches('[data-param-node],[data-node-value]'))this.graphView.snapshot();};
    root.oninput=e=>{let target=e.target;if(target.matches('[data-param-node]')){let n=this.graph.nodes.find(n=>n.id===target.dataset.paramNode);this.graph.set(n.id,'value',Number(target.value));$(`[data-param-output="${n.id}"]`,root).textContent=target.value;}if(target.matches('[data-node-value]')&&node){this.graph.set(node.id,'value',Number(target.value));$('.parameter output',root).textContent=target.value;}};
    root.onchange=e=>{let target=e.target;try{
      if(target.matches('#assign-layer')&&target.value)this.doc.transaction('Change object layers',()=>this.doc.selected().forEach(o=>o.layer=target.value));
      if(object){if(target.matches('[data-object-name]'))this.doc.transaction('Rename object',()=>object.name=target.value);if(target.matches('[data-object-color]'))this.doc.transaction('Object color',()=>object.color=target.value);if(target.matches('[data-object-layer]'))this.doc.transaction('Object layer',()=>object.layer=target.value);if(target.matches('[data-position]'))this.doc.transaction('Set translation',()=>{let i=Number(target.dataset.position),v=Number(target.value);if(!Number.isFinite(v))throw Error('Invalid translation');object.matrix[12+i]=v;this.doc.touch(object);});if(target.matches('[data-geometry-param]'))this.doc.transaction('Set geometry parameter',()=>{let value=Number(target.value);if(!Number.isFinite(value)||value<=0)throw Error('Parameter must be positive');object.geometry[target.dataset.geometryParam]=value;this.doc.touch(object);this.doc.display(object);});if(target.matches('[data-material]'))this.doc.transaction('Edit material',()=>{object.material[target.dataset.material]=clamp(Number(target.value),target.dataset.material==='roughness'?.04:0,1);});}
      if(node){if(target.matches('[data-node-label]'))this.graphView.edit(()=>{node.label=target.value;this.graph.changed('label');this.graphView.render();});if(target.matches('[data-node-property]'))this.graphView.edit(()=>{let key=target.dataset.nodeProperty,value=key==='objectId'?target.value:Number(target.value);if(key!=='objectId'&&!Number.isFinite(value))throw Error('Enter a finite number');if(key==='step'&&value<=0)throw Error('Step must be positive');this.graph.set(node.id,key,value);this.graphView.render();});if(target.matches('[data-node-input]'))this.graphView.edit(()=>{let input=this.graph.registry[node.type].inputs[Number(target.dataset.nodeInput)],value=input.type==='number'?Number(target.value):target.value.split(/[,\s]+/).map(Number);this.graph.set(node.id,input.key,value);});}
    }catch(error){toast(error.message,true);}this.updateInspector(true);};
  }
  showAnalysis(objects){let rows=[];for(let o of objects){let d=this.doc.display(o);if(o.geometry.kind==='curve'){let c=NurbsCurve.from(transformGeometry(o.geometry,o.matrix));rows.push(`<strong>${escape(o.name)}</strong><p>Length: ${c.length(this.doc.tolerance*.1).toFixed(6)} ${this.doc.units}<br>Degree: ${c.degree}<br>Control points: ${c.points.length}</p>`);}else if(d.mesh){let s=analyzeMesh(d.mesh,this.doc.tolerance*.1);rows.push(`<strong>${escape(o.name)}</strong><p>Area: ${s.area.toFixed(4)} ${this.doc.units}²<br>Volume: ${s.closed?s.volume.toFixed(4)+' '+this.doc.units+'³':'Not a closed solid'}<br>Vertices / faces: ${s.vertices} / ${s.faces}<br>Naked edges: ${s.nakedEdges}<br>Non-manifold edges: ${s.nonManifoldEdges}<br>Inconsistent edges: ${s.inconsistentEdges}<br>Closed manifold: ${s.closed?'Yes':'No'}</p>`);}}formDialog('Geometry analysis',[],{description:'',submit:'Close',eyebrow:'VELDRA / ANALYSIS'});$('#dialog-description').innerHTML=rows.join('<hr style="border:0;border-top:1px solid var(--line)">')+'<p class="inspector-note">Mesh area and volume are tessellation-dependent. Closed-edge checks do not test all self-intersections.</p>';}
  showAbout(){formDialog('Veldra 3D',[],{description:'',submit:'Back to workspace',eyebrow:'INDEPENDENT MODELING / 0.1.0'});$('#dialog-description').innerHTML=`<p>A browser-native NURBS modeler with Weave, an integrated visual parametric editor.</p><p>Plain JavaScript, editable double-precision geometry, WebGPU rendering, and no runtime dependencies.</p><p><strong>This release is not a complete production CAD replacement.</strong> It does not implement general trimmed B-rep topology, exact surface booleans, native 3DM / GH compatibility, production meshing guarantees, or third-party plug-in compatibility.</p><p>Rendering: ${escape(this.renderer.backend)}. WebGL2 fallback does not provide GPU surface evaluation or shadow maps.</p><p>Original application code · MIT license</p>`;}
  showHelp(){formDialog('Make something precise',[],{description:'',submit:'Start modeling',eyebrow:'VELDRA / FIELD GUIDE'});$('#dialog-description').innerHTML=`<p><strong>Navigate.</strong> Right-drag to orbit. Middle-drag or Shift-drag to pan. Scroll to zoom. Use Home to frame the model; F to frame selection. Double-click a viewport title to toggle four views.</p><p><strong>Model.</strong> Pick a curve tool, then click the construction plane. Enter finishes a multi-point curve. Esc cancels. Enter exact points as x,y,z in the command line. Primitive commands accept numbers, for example <code>Box 8 6 5</code>.</p><p><strong>Edit.</strong> Select objects in the viewport or Objects panel. Ctrl-click adds to selection. Drag the gumball arrows to translate; use Move, Rotate, or Scale for exact values. Enable Points to drag a NURBS control net. Ctrl+Z undoes an edit.</p><p><strong>Weave.</strong> Change the sliders or double-click the graph to add a component. Drag an output port onto an input. Alt-click an input to disconnect. Select a component to edit defaults. Bake geometry creates independent editable objects and hides those live previews.</p><p><strong>Files.</strong> Save to .veldra for editable models and graphs, or .weave for definitions. OBJ, STL, basic DXF, and glTF exports are available from File. Autosave stays in this browser and is not a substitute for saving a file.</p><p><strong>Find.</strong> Press / for the command palette. Every listed command is implemented; operation-specific limits appear in its dialog or error message.</p>`;}
}
function segmentDistance(p,a,b){let dx=b[0]-a[0],dy=b[1]-a[1],den=dx*dx+dy*dy;if(den<1e-12)return Math.hypot(p[0]-a[0],p[1]-a[1]);let t=clamp(((p[0]-a[0])*dx+(p[1]-a[1])*dy)/den,0,1);return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);}
const app=new VeldraApp();window.veldra=app;app.start().catch(e=>console.error('Veldra startup:',e));
